version: 2
updates:
  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "joluedem"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"

  # GitHub Actions dependencies  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "joluedem"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
