/*
================================================================================
 01-RowCountValidation.sql
 Generated by Cosmos-to-SQL Migration Assessment Tool

 Purpose
   Compare the row count of every migrated table against an expected baseline
   sourced from the Cosmos DB assessment (or operator-supplied overrides).

 Contract with the orchestrator (RunAllValidations.ps1)
   - The orchestrator generates a single GUID once per run and passes it via:
         sqlcmd -v RunId="<guid>" TolerancePctPass=0.5 TolerancePctWarn=5
   - All 6 SQL scripts share that RunId so the report (#197) can join across
     categories.
   - If RunId is the empty GUID, the script generates a local NEWID() so it
     can be run standalone for spot checks. This is for development only --
     a standalone run will NOT appear in the aggregated report.

 Required permissions
   - SELECT on every target schema/table.
   - VIEW DATABASE STATE for the fast metadata path. If absent, the script
     transparently falls back to COUNT_BIG(*) and writes a WARN row.

 Tolerance
   - Status PASS when |delta| <= TolerancePctPass percent.
   - Status WARN when |delta| <= TolerancePctWarn percent.
   - Status FAIL otherwise.

 Conventions
   - All scripts in this folder write to dbo.ValidationResults.
   - This script is the FIRST to run; it creates that table and the
     companion dbo.ValidationExpectedCounts table.
================================================================================
*/

:setvar RunId            "00000000-0000-0000-0000-000000000000"
:setvar TolerancePctPass "0.5"
:setvar TolerancePctWarn "5"
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-------------------------------------------------------------------------------
-- 1. Shared results table (created by 01; reused by 02-06).
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationResults', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationResults
    (
        ResultId      BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ValidationResults PRIMARY KEY,
        RunId         UNIQUEIDENTIFIER NOT NULL,
        Category      NVARCHAR(50)     NOT NULL,
        SchemaName    NVARCHAR(128)    NULL,
        TableName     NVARCHAR(128)    NULL,
        ObjectName    NVARCHAR(256)    NULL,
        CheckName     NVARCHAR(256)    NOT NULL,
        ExpectedValue NVARCHAR(MAX)    NULL,
        ActualValue   NVARCHAR(MAX)    NULL,
        Status        NVARCHAR(16)     NOT NULL,
        Details       NVARCHAR(MAX)    NULL,
        CapturedAt    DATETIME2(3)     NOT NULL CONSTRAINT DF_ValidationResults_CapturedAt DEFAULT SYSUTCDATETIME()
    );

    CREATE INDEX IX_ValidationResults_RunId_Category
        ON dbo.ValidationResults (RunId, Category)
        INCLUDE (Status, SchemaName, TableName);
END;
GO

-------------------------------------------------------------------------------
-- 2. Expected counts table (managed by 01; populated below + by orchestrator).
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationExpectedCounts', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationExpectedCounts
    (
        SchemaName   NVARCHAR(128) NOT NULL,
        TableName    NVARCHAR(128) NOT NULL,
        Source       NVARCHAR(32)  NOT NULL,
        ExpectedRows BIGINT        NULL,
        CapturedAt   DATETIME2(3)  NOT NULL CONSTRAINT DF_ValidationExpectedCounts_CapturedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_ValidationExpectedCounts PRIMARY KEY (SchemaName, TableName, Source)
    );
END;
GO

-------------------------------------------------------------------------------
-- 3. Reusable per-table comparison procedure.
--    Encapsulates the dual-strategy count (fast DMV first, exact COUNT_BIG(*)
--    on mismatch or when the caller lacks VIEW DATABASE STATE).
-------------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE dbo.sp_ValidationRowCountCheck
    @RunId             UNIQUEIDENTIFIER,
    @SchemaName        SYSNAME,
    @TableName         SYSNAME,
    @CanUseDmv         BIT,
    @TolerancePctPass  DECIMAL(9,4),
    @TolerancePctWarn  DECIMAL(9,4)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ObjectId     INT          = OBJECT_ID(QUOTENAME(@SchemaName) + N'.' + QUOTENAME(@TableName));
    DECLARE @FullName     NVARCHAR(260) = QUOTENAME(@SchemaName) + N'.' + QUOTENAME(@TableName);
    DECLARE @Expected     BIGINT;
    DECLARE @Actual       BIGINT;
    DECLARE @Source       NVARCHAR(32);
    DECLARE @Status       NVARCHAR(16);
    DECLARE @Details      NVARCHAR(MAX);

    IF @ObjectId IS NULL
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'RowCount', @SchemaName, @TableName, N'TableExists', N'FAIL',
                N'Target table ' + @FullName + N' does not exist.');
        RETURN;
    END;

    -- Pick the expected value: override beats assessment.
    SELECT TOP (1) @Expected = ExpectedRows, @Source = Source
    FROM   dbo.ValidationExpectedCounts
    WHERE  SchemaName = @SchemaName AND TableName = @TableName
    ORDER BY CASE Source WHEN N'Override' THEN 0 WHEN N'Assessment' THEN 1 ELSE 2 END;

    -- Fast metadata path.
    IF @CanUseDmv = 1
    BEGIN
        SELECT @Actual = SUM(row_count)
        FROM   sys.dm_db_partition_stats
        WHERE  object_id = @ObjectId
          AND  index_id IN (0, 1);
    END;

    -- Exact fallback when DMV unavailable, missing, or mismatched.
    IF @CanUseDmv = 0
        OR @Actual IS NULL
        OR (@Expected IS NOT NULL AND @Actual <> @Expected)
    BEGIN
        DECLARE @Sql NVARCHAR(MAX) =
            N'SELECT @cnt = COUNT_BIG(*) FROM ' + @FullName + N' WITH (NOLOCK);';
        EXEC sys.sp_executesql @Sql, N'@cnt BIGINT OUTPUT', @cnt = @Actual OUTPUT;
    END;

    IF @Expected IS NULL
    BEGIN
        SET @Status  = N'WARN';
        SET @Details = N'No expected baseline (assessment or override) for ' + @FullName + N'.';
    END
    ELSE IF @Expected = 0 AND @Actual > 0
    BEGIN
        SET @Status  = N'WARN';
        SET @Details = N'Assessment baseline was 0; actual is ' + CAST(@Actual AS NVARCHAR(20))
                     + N'. Container likely populated after assessment.';
    END
    ELSE
    BEGIN
        DECLARE @DeltaPct DECIMAL(18,6) =
            CASE
                WHEN @Expected = 0 THEN CASE WHEN @Actual = 0 THEN 0 ELSE 100 END
                ELSE ABS(CAST(@Actual - @Expected AS DECIMAL(38,6)) * 100.0
                         / NULLIF(CAST(@Expected AS DECIMAL(38,6)), 0))
            END;

        SET @Status =
            CASE
                WHEN @DeltaPct <= @TolerancePctPass THEN N'PASS'
                WHEN @DeltaPct <= @TolerancePctWarn THEN N'WARN'
                ELSE N'FAIL'
            END;

        SET @Details = N'Delta=' + CAST(@DeltaPct AS NVARCHAR(40)) + N'% (tolerance pass<='
                     + CAST(@TolerancePctPass AS NVARCHAR(20)) + N'%, warn<='
                     + CAST(@TolerancePctWarn AS NVARCHAR(20)) + N'%) source='
                     + ISNULL(@Source, N'(none)');
    END;

    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, CheckName, ExpectedValue, ActualValue, Status, Details)
    VALUES
        (@RunId, N'RowCount', @SchemaName, @TableName, N'RowCount',
         CASE WHEN @Expected IS NULL THEN NULL ELSE CAST(@Expected AS NVARCHAR(50)) END,
         CASE WHEN @Actual   IS NULL THEN NULL ELSE CAST(@Actual   AS NVARCHAR(50)) END,
         @Status, @Details);
END;
GO

-------------------------------------------------------------------------------
-- 4. Main validation batch: resolve RunId, seed expected counts, compare.
-------------------------------------------------------------------------------
BEGIN
    DECLARE @RunId UNIQUEIDENTIFIER = TRY_CAST(N'$(RunId)' AS UNIQUEIDENTIFIER);
    IF @RunId IS NULL OR @RunId = CAST(N'00000000-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
    BEGIN
        SET @RunId = NEWID();
        PRINT N'WARNING: No orchestrator RunId supplied; generated local RunId = '
              + CONVERT(NVARCHAR(36), @RunId)
              + N'. Standalone run -- results will not appear in the cross-script report.';
    END;

    DECLARE @TolerancePctPass DECIMAL(9,4) = ISNULL(TRY_CAST(N'$(TolerancePctPass)' AS DECIMAL(9,4)), 0.5);
    DECLARE @TolerancePctWarn DECIMAL(9,4) = ISNULL(TRY_CAST(N'$(TolerancePctWarn)' AS DECIMAL(9,4)), 5.0);

    -- Permission pre-flight.
    DECLARE @CanUseDmv BIT = ISNULL(HAS_PERMS_BY_NAME(NULL, NULL, N'VIEW DATABASE STATE'), 0);
    IF @CanUseDmv = 0
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, CheckName, Status, Details)
        VALUES (@RunId, N'RowCount', N'PreflightPermissionCheck', N'WARN',
                N'Caller lacks VIEW DATABASE STATE; falling back to COUNT_BIG(*) for every table.');
    END;

    -- Seed expected counts from the assessment. Idempotent: assessment rows are
    -- replaced on every run. Override rows (Source='Override') are owned by the
    -- orchestrator (#198) and left alone here.
    -- {{ExpectedCountsSeed}} -- generator inserts MERGE statements here
{{ExpectedCountsSeed}}

    -- Per-table comparison. The generator emits one block per migrated table.
    -- Each block calls dbo.sp_ValidationRowCountCheck (created just below).
    -- {{TableRowsBlock}} -- generator inserts EXEC calls here
{{TableRowsBlock}}

    -- Summary.
    DECLARE @Pass INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'RowCount' AND Status = N'PASS');
    DECLARE @Warn INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'RowCount' AND Status = N'WARN');
    DECLARE @Fail INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'RowCount' AND Status = N'FAIL');
    DECLARE @Info INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'RowCount' AND Status = N'INFO');
    PRINT N'[RowCount] RunId=' + CONVERT(NVARCHAR(36), @RunId)
        + N' Pass=' + CAST(@Pass AS NVARCHAR(20))
        + N' Warn=' + CAST(@Warn AS NVARCHAR(20))
        + N' Fail=' + CAST(@Fail AS NVARCHAR(20))
        + N' Info=' + CAST(@Info AS NVARCHAR(20));
END;
GO
