/*
================================================================================
 02-DataIntegrityChecks.sql
 Generated by Cosmos-to-SQL Migration Assessment Tool

 Purpose
   Produce a deterministic per-table data fingerprint (SHA2-256 per row, then
   CHECKSUM_AGG of the per-row hashes) and compare it to a baseline computed
   on the source Cosmos data.

 Contract for cross-platform reproducibility
   - Per-row hash: SHA2-256 over CONCAT_WS('||', col1, col2, ...).
   - Each column is cast to VARCHAR(MAX) so the hashed byte stream is UTF-8
     compatible (NVARCHAR would hash UTF-16LE bytes and never match a Python
     baseline).
   - NULLs are replaced by the literal string '\N' BEFORE concatenation so
     ('a', NULL, 'b') and ('a', 'b', NULL) produce distinct hashes.
   - Aggregate: CHECKSUM_AGG(CHECKSUM(rowhash)) -- commutative, no parallel
     plan ordering hazard. Trade-off: aggregate collision-resistance is
     CHECKSUM-level, not SHA2-level, but the per-row SHA2 already catches
     any single-row mutation.
   - To reproduce against Cosmos: order docs by the same key, project the
     same field set in the same order, convert each field to its UTF-8
     string form ('\N' for null), join with '||', SHA2-256 each row, then
     XOR all hash values interpreted as little-endian INT32 (first 4 bytes,
     matching SQL Server's CHECKSUM(varbinary) semantics).

 Status semantics
   ExpectedHash IS NULL         -> INFO  (fingerprint only)
   ActualHash  =  ExpectedHash  -> PASS
   otherwise                    -> FAIL

 Sampling
   :setvar SampleRows 10000     (0 = full table)
   Uses TOP (@SampleRows) with a deterministic ORDER BY so re-runs produce
   the same hash.

 Required permissions
   - SELECT on every target schema/table.
================================================================================
*/

:setvar RunId      "00000000-0000-0000-0000-000000000000"
:setvar SampleRows "10000"
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-------------------------------------------------------------------------------
-- 1. Expected checksums table (managed here; reused by orchestrator overrides).
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationExpectedChecksums', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationExpectedChecksums
    (
        SchemaName    NVARCHAR(128) NOT NULL,
        TableName     NVARCHAR(128) NOT NULL,
        Source        NVARCHAR(32)  NOT NULL,   -- 'Operator'
        SampleRows    BIGINT        NOT NULL,
        AlgorithmName NVARCHAR(32)  NOT NULL CONSTRAINT DF_VECk_Algo DEFAULT N'SHA2_256+CHECKSUM_AGG',
        ExpectedHash  NVARCHAR(64)  NOT NULL,
        CapturedAt    DATETIME2(3)  NOT NULL CONSTRAINT DF_VECk_CapturedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_ValidationExpectedChecksums PRIMARY KEY (SchemaName, TableName, Source)
    );
END;
GO

-------------------------------------------------------------------------------
-- 2. Reusable per-table checksum procedure.
-------------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE dbo.sp_ValidationChecksum
    @RunId        UNIQUEIDENTIFIER,
    @SchemaName   SYSNAME,
    @TableName    SYSNAME,
    @SampleRows   BIGINT,
    @ColumnList   NVARCHAR(MAX),    -- pre-rendered CONCAT_WS argument list
    @OrderBy      NVARCHAR(MAX)     -- ORDER BY clause (no leading 'ORDER BY')
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ObjectId   INT          = OBJECT_ID(QUOTENAME(@SchemaName) + N'.' + QUOTENAME(@TableName));
    DECLARE @FullName   NVARCHAR(260) = QUOTENAME(@SchemaName) + N'.' + QUOTENAME(@TableName);

    IF @ObjectId IS NULL
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Checksum', @SchemaName, @TableName, N'TableExists', N'FAIL',
                N'Target table ' + @FullName + N' does not exist.');
        RETURN;
    END;

    IF @ColumnList IS NULL OR LTRIM(RTRIM(@ColumnList)) = N''
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Checksum', @SchemaName, @TableName, N'ColumnList', N'INFO',
                N'No column metadata available in the assessment; checksum skipped.');
        RETURN;
    END;

    DECLARE @TopClause NVARCHAR(64) =
        CASE WHEN @SampleRows > 0 THEN N'TOP (' + CAST(@SampleRows AS NVARCHAR(20)) + N') ' ELSE N'' END;

    DECLARE @Sql NVARCHAR(MAX) = N'
        DECLARE @AggInt BIGINT;
        DECLARE @Count  BIGINT;
        SELECT @AggInt = SUM(CAST(CHECKSUM(RowHash) AS BIGINT)),
               @Count  = COUNT_BIG(*)
        FROM (
            SELECT ' + @TopClause + N'HASHBYTES(N''SHA2_256'', CONCAT_WS(''||'', ' + @ColumnList + N')) AS RowHash
            FROM   ' + @FullName + N'
            ORDER  BY ' + @OrderBy + N'
        ) AS s;
        SELECT @AggInt AS AggInt, @Count AS RowCount;';

    DECLARE @Result TABLE (AggInt BIGINT, [RowCount] BIGINT);
    BEGIN TRY
        INSERT @Result (AggInt, [RowCount])
        EXEC sys.sp_executesql @Sql;
    END TRY
    BEGIN CATCH
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Checksum', @SchemaName, @TableName, N'ExecuteHash', N'FAIL',
                N'Error computing checksum for ' + @FullName + N': ' + ERROR_MESSAGE());
        RETURN;
    END CATCH;

    DECLARE @Agg BIGINT, @Rows BIGINT;
    SELECT TOP (1) @Agg = AggInt, @Rows = [RowCount] FROM @Result;

    -- Hex-encoded fingerprint (16 hex chars; signed BIGINT representation).
    DECLARE @ActualHash NVARCHAR(64) = CONVERT(NVARCHAR(64), CAST(@Agg AS VARBINARY(8)), 2);

    DECLARE @Expected NVARCHAR(64);
    DECLARE @ExpectedSample BIGINT;
    SELECT TOP (1) @Expected = ExpectedHash, @ExpectedSample = SampleRows
    FROM   dbo.ValidationExpectedChecksums
    WHERE  SchemaName = @SchemaName AND TableName = @TableName;

    DECLARE @Status  NVARCHAR(16);
    DECLARE @Details NVARCHAR(MAX);

    IF @Expected IS NULL
    BEGIN
        SET @Status  = N'INFO';
        SET @Details = N'Fingerprint captured (' + CAST(@Rows AS NVARCHAR(20))
                     + N' rows hashed). No operator-supplied baseline.';
    END
    ELSE IF @ExpectedSample <> @SampleRows
    BEGIN
        SET @Status  = N'WARN';
        SET @Details = N'SampleRows mismatch: actual=' + CAST(@SampleRows AS NVARCHAR(20))
                     + N' expected=' + CAST(@ExpectedSample AS NVARCHAR(20));
    END
    ELSE IF @ActualHash = @Expected
    BEGIN
        SET @Status  = N'PASS';
        SET @Details = N'Hashes match (' + CAST(@Rows AS NVARCHAR(20)) + N' rows).';
    END
    ELSE
    BEGIN
        SET @Status  = N'FAIL';
        SET @Details = N'Hash mismatch (' + CAST(@Rows AS NVARCHAR(20)) + N' rows hashed).';
    END;

    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, CheckName, ExpectedValue, ActualValue, Status, Details)
    VALUES
        (@RunId, N'Checksum', @SchemaName, @TableName, N'Fingerprint',
         @Expected, @ActualHash, @Status, @Details);
END;
GO

-------------------------------------------------------------------------------
-- 3. Main validation batch.
-------------------------------------------------------------------------------
BEGIN
    DECLARE @RunId UNIQUEIDENTIFIER = TRY_CAST(N'$(RunId)' AS UNIQUEIDENTIFIER);
    IF @RunId IS NULL OR @RunId = CAST(N'00000000-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
    BEGIN
        SET @RunId = NEWID();
        PRINT N'WARNING: No orchestrator RunId supplied; generated local RunId = '
              + CONVERT(NVARCHAR(36), @RunId)
              + N'. Standalone run -- results will not appear in the cross-script report.';
    END;

    DECLARE @SampleRows BIGINT = ISNULL(TRY_CAST(N'$(SampleRows)' AS BIGINT), 10000);

    -- Per-table EXEC calls.
    -- {{ChecksumChecksBlock}}
{{ChecksumChecksBlock}}

    DECLARE @Pass INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Checksum' AND Status = N'PASS');
    DECLARE @Warn INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Checksum' AND Status = N'WARN');
    DECLARE @Fail INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Checksum' AND Status = N'FAIL');
    DECLARE @Info INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Checksum' AND Status = N'INFO');
    PRINT N'[Checksum] RunId=' + CONVERT(NVARCHAR(36), @RunId)
        + N' Pass=' + CAST(@Pass AS NVARCHAR(20))
        + N' Warn=' + CAST(@Warn AS NVARCHAR(20))
        + N' Fail=' + CAST(@Fail AS NVARCHAR(20))
        + N' Info=' + CAST(@Info AS NVARCHAR(20));
END;
GO
