/*
================================================================================
 03-SampleDataComparison.sql
 Generated by Cosmos-to-SQL Migration Assessment Tool

 Purpose
   Capture the first-N and last-N rows of each migrated table (ordered by a
   deterministic key) as JSON snapshots, then compare each snapshot row to an
   operator-supplied baseline from the source Cosmos dataset.

 Snapshot table
   dbo.ValidationSampleRows
     - RunId      : groups rows belonging to one validation run.
     - Position   : 'First' | 'Last'.
     - Ordinal    : 1..N (1 = top row of the ASC/DESC sort).
     - KeyHash    : SHA2-256 of the ORDER BY key tuple (PK shift detector).
     - RowJson    : FOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER.

 Baseline table (populated externally by the orchestrator)
   dbo.ValidationExpectedSampleRows
     - Same shape, scoped by RunId.
     - The orchestrator MUST re-serialize Cosmos documents with the same
       column projection AND in the same column order used by this script.
       Missing properties are serialized as JSON null (matching
       INCLUDE_NULL_VALUES). Without that contract, the per-property diff
       below will report false positives for property-order or
       null-vs-missing discrepancies.

 Comparison semantics (per (Schema, Table, Position, Ordinal))
   - actual NULL, expected NULL : row not emitted (nothing to compare).
   - actual present, expected NULL : INFO  (no baseline supplied).
   - actual NULL, expected present : FAIL  (row missing in target).
   - both present, KeyHash differs : WARN  (row shift; values not compared).
   - both present, all OPENJSON keys/values equal : PASS.
   - otherwise : FAIL, with the differing column names listed in Details.

 Child tables
   Skipped here (no unique sort key in the assessment model). An INFO row
   per child explains the skip so the report shows the gap.

 Sampling tuning
   :setvar SampleRows 10     (no upper bound; keep small for diff-by-eye)

 Required permissions
   - SELECT on every target schema/table.
================================================================================
*/

:setvar RunId      "00000000-0000-0000-0000-000000000000"
:setvar SampleRows "10"
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-------------------------------------------------------------------------------
-- 1. Snapshot + baseline tables.
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationSampleRows', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationSampleRows
    (
        SampleId    BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_ValidationSampleRows PRIMARY KEY,
        RunId       UNIQUEIDENTIFIER NOT NULL,
        SchemaName  NVARCHAR(128)    NOT NULL,
        TableName   NVARCHAR(128)    NOT NULL,
        Position    NVARCHAR(8)      NOT NULL,
        Ordinal     INT              NOT NULL,
        KeyHash     NVARCHAR(64)     NOT NULL,
        RowJson     NVARCHAR(MAX)    NOT NULL,
        CapturedAt  DATETIME2(3)     NOT NULL
            CONSTRAINT DF_VSampleRows_CapturedAt DEFAULT SYSUTCDATETIME()
    );

    CREATE INDEX IX_ValidationSampleRows_Lookup
        ON dbo.ValidationSampleRows (RunId, SchemaName, TableName, Position, Ordinal);
END;
GO

IF OBJECT_ID(N'dbo.ValidationExpectedSampleRows', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationExpectedSampleRows
    (
        RunId       UNIQUEIDENTIFIER NOT NULL,
        SchemaName  NVARCHAR(128)    NOT NULL,
        TableName   NVARCHAR(128)    NOT NULL,
        Position    NVARCHAR(8)      NOT NULL,
        Ordinal     INT              NOT NULL,
        KeyHash     NVARCHAR(64)     NOT NULL,
        RowJson     NVARCHAR(MAX)    NOT NULL,
        CapturedAt  DATETIME2(3)     NOT NULL
            CONSTRAINT DF_VExpectedSampleRows_CapturedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_ValidationExpectedSampleRows
            PRIMARY KEY (RunId, SchemaName, TableName, Position, Ordinal)
    );
END;
GO

-------------------------------------------------------------------------------
-- 2. Reusable per-table sample capture procedure.
-------------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE dbo.sp_ValidationSampleCapture
    @RunId        UNIQUEIDENTIFIER,
    @SchemaName   SYSNAME,
    @TableName    SYSNAME,
    @SampleRows   INT,
    @ColumnList   NVARCHAR(MAX),    -- pre-rendered column list (no SELECT)
    @OrderByAsc   NVARCHAR(MAX),    -- ORDER BY clause for First N (no 'ORDER BY')
    @OrderByDesc  NVARCHAR(MAX),    -- ORDER BY clause for Last  N (no 'ORDER BY')
    @KeyExpr      NVARCHAR(MAX)     -- expression evaluated per row for KeyHash
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @FullName NVARCHAR(260) = QUOTENAME(@SchemaName) + N'.' + QUOTENAME(@TableName);

    IF OBJECT_ID(@FullName) IS NULL
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Sample', @SchemaName, @TableName, N'TableExists', N'FAIL',
                N'Target table ' + @FullName + N' does not exist.');
        RETURN;
    END;

    IF @SampleRows IS NULL OR @SampleRows <= 0
        SET @SampleRows = 10;

    DECLARE @CaptureSql NVARCHAR(MAX);

    -- First N (ASC) ----------------------------------------------------------
    SET @CaptureSql = N'
        ;WITH src AS (
            SELECT TOP (@N) ' + @ColumnList + N',
                   CONVERT(NVARCHAR(64),
                           HASHBYTES(N''SHA2_256'', CONVERT(VARBINARY(MAX), ' + @KeyExpr + N')),
                           2) AS __KeyHash
            FROM   ' + @FullName + N' WITH (NOLOCK)
            ORDER  BY ' + @OrderByAsc + N'
        ),
        numbered AS (
            SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS __Ord,
                   __KeyHash,
                   ' + @ColumnList + N'
            FROM   src
        )
        INSERT INTO dbo.ValidationSampleRows
            (RunId, SchemaName, TableName, Position, Ordinal, KeyHash, RowJson)
        SELECT @RunId, @Schema, @Table, N''First'', n.__Ord, n.__KeyHash,
               (SELECT ' + @ColumnList + N'
                FOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER)
        FROM   numbered AS n;';

    BEGIN TRY
        EXEC sys.sp_executesql @CaptureSql,
            N'@N INT, @RunId UNIQUEIDENTIFIER, @Schema SYSNAME, @Table SYSNAME',
            @N = @SampleRows, @RunId = @RunId, @Schema = @SchemaName, @Table = @TableName;
    END TRY
    BEGIN CATCH
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Sample', @SchemaName, @TableName, N'CaptureFirst', N'FAIL',
                N'Error capturing First-N sample for ' + @FullName + N': ' + ERROR_MESSAGE());
        RETURN;
    END CATCH;

    -- Last N (DESC) ----------------------------------------------------------
    SET @CaptureSql = N'
        ;WITH src AS (
            SELECT TOP (@N) ' + @ColumnList + N',
                   CONVERT(NVARCHAR(64),
                           HASHBYTES(N''SHA2_256'', CONVERT(VARBINARY(MAX), ' + @KeyExpr + N')),
                           2) AS __KeyHash
            FROM   ' + @FullName + N' WITH (NOLOCK)
            ORDER  BY ' + @OrderByDesc + N'
        ),
        numbered AS (
            SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS __Ord,
                   __KeyHash,
                   ' + @ColumnList + N'
            FROM   src
        )
        INSERT INTO dbo.ValidationSampleRows
            (RunId, SchemaName, TableName, Position, Ordinal, KeyHash, RowJson)
        SELECT @RunId, @Schema, @Table, N''Last'', n.__Ord, n.__KeyHash,
               (SELECT ' + @ColumnList + N'
                FOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER)
        FROM   numbered AS n;';

    BEGIN TRY
        EXEC sys.sp_executesql @CaptureSql,
            N'@N INT, @RunId UNIQUEIDENTIFIER, @Schema SYSNAME, @Table SYSNAME',
            @N = @SampleRows, @RunId = @RunId, @Schema = @SchemaName, @Table = @TableName;
    END TRY
    BEGIN CATCH
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Sample', @SchemaName, @TableName, N'CaptureLast', N'FAIL',
                N'Error capturing Last-N sample for ' + @FullName + N': ' + ERROR_MESSAGE());
        RETURN;
    END CATCH;

    -- Surface empty tables explicitly so the report shows the gap. ----------
    IF NOT EXISTS (
        SELECT 1 FROM dbo.ValidationSampleRows
        WHERE RunId = @RunId AND SchemaName = @SchemaName AND TableName = @TableName
    )
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, CheckName, Status, Details)
        VALUES (@RunId, N'Sample', @SchemaName, @TableName, N'SampleCapture', N'INFO',
                N'Table ' + @FullName + N' is empty; no sample rows captured.');
    END;
END;
GO

-------------------------------------------------------------------------------
-- 3. Main validation batch.
-------------------------------------------------------------------------------
BEGIN
    DECLARE @RunId UNIQUEIDENTIFIER = TRY_CAST(N'$(RunId)' AS UNIQUEIDENTIFIER);
    IF @RunId IS NULL OR @RunId = CAST(N'00000000-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
    BEGIN
        SET @RunId = NEWID();
        PRINT N'WARNING: No orchestrator RunId supplied; generated local RunId = '
              + CONVERT(NVARCHAR(36), @RunId)
              + N'. Standalone run -- results will not appear in the cross-script report.';
    END;

    DECLARE @SampleRows INT = ISNULL(TRY_CAST(N'$(SampleRows)' AS INT), 10);
    IF @SampleRows <= 0 SET @SampleRows = 10;

    -- Per-table EXEC calls + child-table skip notices.
    -- {{SampleCaptureBlock}}
{{SampleCaptureBlock}}

    -------------------------------------------------------------------------
    -- 4. Diff snapshot vs operator-supplied baseline (FULL OUTER JOIN so
    --    rows missing on either side surface as INFO/FAIL respectively).
    -------------------------------------------------------------------------
    ;WITH actual_cur AS (
        SELECT SchemaName, TableName, Position, Ordinal, KeyHash, RowJson
        FROM   dbo.ValidationSampleRows
        WHERE  RunId = @RunId
    ),
    expected_cur AS (
        SELECT SchemaName, TableName, Position, Ordinal, KeyHash, RowJson
        FROM   dbo.ValidationExpectedSampleRows
        WHERE  RunId = @RunId
    ),
    joined AS (
        SELECT COALESCE(a.SchemaName, e.SchemaName) AS SchemaName,
               COALESCE(a.TableName,  e.TableName)  AS TableName,
               COALESCE(a.Position,   e.Position)   AS Position,
               COALESCE(a.Ordinal,    e.Ordinal)    AS Ordinal,
               a.KeyHash AS ActualKeyHash,
               e.KeyHash AS ExpectedKeyHash,
               a.RowJson AS ActualJson,
               e.RowJson AS ExpectedJson
        FROM   actual_cur   AS a
        FULL OUTER JOIN expected_cur AS e
               ON  a.SchemaName = e.SchemaName
              AND  a.TableName  = e.TableName
              AND  a.Position   = e.Position
              AND  a.Ordinal    = e.Ordinal
    )
    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Sample',
            j.SchemaName, j.TableName,
            j.Position + N'#' + CAST(j.Ordinal AS NVARCHAR(10)),
            N'SampleRow',
            CASE WHEN j.ExpectedJson IS NULL THEN NULL
                 WHEN LEN(j.ExpectedJson) > 500
                      THEN LEFT(j.ExpectedJson, 500) + N'...'
                 ELSE j.ExpectedJson END,
            CASE WHEN j.ActualJson IS NULL THEN NULL
                 WHEN LEN(j.ActualJson) > 500
                      THEN LEFT(j.ActualJson, 500) + N'...'
                 ELSE j.ActualJson END,
            CASE WHEN j.ActualJson   IS NULL THEN N'FAIL'
                 WHEN j.ExpectedJson IS NULL THEN N'INFO'
                 WHEN j.ActualKeyHash <> j.ExpectedKeyHash THEN N'WARN'
                 WHEN ISNULL(diffs.MismatchCount, 0) = 0 THEN N'PASS'
                 ELSE N'FAIL' END,
            CASE WHEN j.ActualJson   IS NULL THEN N'Row missing in target'
                 WHEN j.ExpectedJson IS NULL THEN N'No baseline supplied for this position'
                 WHEN j.ActualKeyHash <> j.ExpectedKeyHash
                      THEN N'Key shift: expected ' + ISNULL(j.ExpectedKeyHash, N'<null>')
                         + N', actual ' + ISNULL(j.ActualKeyHash, N'<null>')
                         + N' -- values not compared'
                 WHEN ISNULL(diffs.MismatchCount, 0) = 0 THEN N'All properties match'
                 ELSE CAST(diffs.MismatchCount AS NVARCHAR(10))
                    + N' column(s) differ: ' + diffs.MismatchedCols END
    FROM    joined AS j
    OUTER APPLY (
        SELECT COUNT(*) AS MismatchCount,
               STRING_AGG(d.col, N', ') WITHIN GROUP (ORDER BY d.col) AS MismatchedCols
        FROM (
            SELECT COALESCE(act.[key], exp.[key]) AS col
            FROM   OPENJSON(ISNULL(j.ActualJson,   N'{}')) AS act
            FULL OUTER JOIN OPENJSON(ISNULL(j.ExpectedJson, N'{}')) AS exp
                   ON exp.[key] = act.[key]
            WHERE  ISNULL(act.[value], N'~~NULL~~') COLLATE Latin1_General_BIN2
                <> ISNULL(exp.[value], N'~~NULL~~') COLLATE Latin1_General_BIN2
        ) AS d
    ) AS diffs;

    DECLARE @Pass INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Sample' AND Status = N'PASS');
    DECLARE @Warn INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Sample' AND Status = N'WARN');
    DECLARE @Fail INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Sample' AND Status = N'FAIL');
    DECLARE @Info INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'Sample' AND Status = N'INFO');
    PRINT N'[Sample] RunId=' + CONVERT(NVARCHAR(36), @RunId)
        + N' Pass=' + CAST(@Pass AS NVARCHAR(20))
        + N' Warn=' + CAST(@Warn AS NVARCHAR(20))
        + N' Fail=' + CAST(@Fail AS NVARCHAR(20))
        + N' Info=' + CAST(@Info AS NVARCHAR(20));
END;
GO
