/*
================================================================================
 04-PerformanceBaseline.sql
 Generated by Cosmos-to-SQL Migration Assessment Tool

 Purpose
   Post-migration performance baseline. Observational only -- captures the
   *current* state of database health into dbo.ValidationResults so the
   operator has a baseline to compare against on subsequent runs.

 Sections
   01. TableSize          -- per-mapped-table row & page counts (sys.dm_db_partition_stats)
   02. IndexCount         -- per-table NC index count (sys.indexes)
   03. PlanCacheWarmth    -- gating INFO row about plan cache fullness
   04. WaitStats          -- top 20 waits from sys.dm_db_wait_stats (excl. benign)
   05. TopCpu             -- top 20 plan-cache entries by total CPU, scoped to mapped tables
   06. TopDuration        -- top 20 plan-cache entries by total elapsed, scoped to mapped tables
   07. MissingIndex       -- missing-index suggestions, scoped to mapped tables
   08. MissingIndexDmvAge -- INFO row with sqlserver_start_time for context
   09. StatsFreshness     -- STATS_DATE per stat on mapped tables
   10. Summary

 Permissions
   - SELECT on every mapped schema/table.
   - VIEW DATABASE STATE for DMV access (sections 03-09).
     Pre-flight check emits a WARN + skip if absent.

 Notes
   - All rows are INFO by default. The following thresholds escalate to WARN:
       * Stats older than 30 days on a table with > 100k rows
       * STATS_DATE IS NULL on a table with > 100k rows
       * Missing-index improvement_measure > :setvar MissingIndexWarnThreshold
       * Any wait type in (PAGEIOLATCH_*) > 10% of total signal wait time

   - Plan-cache filtering uses LIKE on sys.dm_exec_sql_text -- this is
     approximate (a string literal containing a table name will false-positive).
     Acceptable for a baseline; use Query Store for precise attribution.

   - The plan cache is bounded and resets on Azure SQL DB maintenance restarts.
     Run this after at least 1 hour of representative workload.

   - Fragmentation (sys.dm_db_index_physical_stats) is deferred to a separate
     index-health script -- LIMITED mode still scans index pages and can be
     expensive on large tables.

 Re-use
   Re-uses dbo.ValidationFkScopeTables (created by 06-ForeignKeyValidation.sql)
   to scope to assessment-mapped tables only. Re-creates it if missing.
================================================================================
*/

:setvar RunId                       "00000000-0000-0000-0000-000000000000"
:setvar MissingIndexWarnThreshold   "100000"
:setvar MaxScopeTablesForPlanCache  "50"
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-------------------------------------------------------------------------------
-- 1. Seed scope table (idempotent).
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationFkScopeTables', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationFkScopeTables
    (
        SchemaName NVARCHAR(128) NOT NULL,
        TableName  NVARCHAR(128) NOT NULL,
        CONSTRAINT PK_ValidationFkScopeTables PRIMARY KEY (SchemaName, TableName)
    );
END;
GO

-------------------------------------------------------------------------------
-- 2. Main batch.
-------------------------------------------------------------------------------
BEGIN
    DECLARE @RunId UNIQUEIDENTIFIER = TRY_CAST(N'$(RunId)' AS UNIQUEIDENTIFIER);
    IF @RunId IS NULL OR @RunId = CAST(N'00000000-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
    BEGIN
        SET @RunId = NEWID();
        PRINT N'WARNING: No orchestrator RunId supplied; generated local RunId = '
              + CONVERT(NVARCHAR(36), @RunId)
              + N'. Standalone run -- results will not appear in the cross-script report.';
    END;

    DECLARE @MissingIndexWarn BIGINT = ISNULL(TRY_CAST(N'$(MissingIndexWarnThreshold)' AS BIGINT), 100000);
    DECLARE @MaxScopeForCache INT    = ISNULL(TRY_CAST(N'$(MaxScopeTablesForPlanCache)' AS INT), 50);
    DECLARE @HasVds BIT              = CASE WHEN HAS_PERMS_BY_NAME(NULL, NULL, 'VIEW DATABASE STATE') = 1
                                            THEN 1 ELSE 0 END;

    -- {{ScopeTablesSeed}}
{{ScopeTablesSeed}}

    -----------------------------------------------------------------------
    -- 2a. TableSize
    -----------------------------------------------------------------------
    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Performance',
            sc.SchemaName, sc.TableName, N'TableSize',
            N'(observational)',
            CAST(ISNULL(SUM(ps.row_count), 0)             AS NVARCHAR(20))
            + N' rows; '
            + CAST(ISNULL(SUM(ps.used_page_count), 0) * 8 AS NVARCHAR(20))
            + N' KB used',
            N'INFO',
            N'Pages used: ' + CAST(ISNULL(SUM(ps.used_page_count), 0)  AS NVARCHAR(20))
            + N'; total: '  + CAST(ISNULL(SUM(ps.reserved_page_count), 0) AS NVARCHAR(20))
            + N'.'
    FROM    dbo.ValidationFkScopeTables AS sc
    LEFT    JOIN sys.tables   AS t  ON t.name = sc.TableName
                                    AND SCHEMA_NAME(t.schema_id) = sc.SchemaName
    LEFT    JOIN sys.dm_db_partition_stats AS ps
            ON  ps.object_id = t.object_id
            AND ps.index_id IN (0, 1)  -- HEAP or clustered = base data
    GROUP BY sc.SchemaName, sc.TableName;

    -----------------------------------------------------------------------
    -- 2b. IndexCount
    -----------------------------------------------------------------------
    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Performance',
            sc.SchemaName, sc.TableName, N'IndexCount',
            N'(observational)',
            CAST(ISNULL(SUM(CASE WHEN i.type_desc = N'NONCLUSTERED' THEN 1 ELSE 0 END), 0) AS NVARCHAR(10)) + N' NC; '
            + CAST(ISNULL(SUM(CASE WHEN i.type_desc = N'CLUSTERED'    THEN 1 ELSE 0 END), 0) AS NVARCHAR(10)) + N' CL; '
            + CAST(ISNULL(SUM(CASE WHEN i.type_desc LIKE N'%COLUMNSTORE%' THEN 1 ELSE 0 END), 0) AS NVARCHAR(10)) + N' CS',
            N'INFO',
            N'Index count by type for ' + sc.SchemaName + N'.' + sc.TableName + N'.'
    FROM    dbo.ValidationFkScopeTables AS sc
    LEFT    JOIN sys.tables  AS t ON t.name = sc.TableName
                                  AND SCHEMA_NAME(t.schema_id) = sc.SchemaName
    LEFT    JOIN sys.indexes AS i ON i.object_id = t.object_id
                                  AND i.type_desc <> N'HEAP'
                                  AND i.is_hypothetical = 0
    GROUP BY sc.SchemaName, sc.TableName;

    -----------------------------------------------------------------------
    -- 2c. PlanCacheWarmth gating row
    -----------------------------------------------------------------------
    IF @HasVds = 1
    BEGIN
        DECLARE @PlanCount INT = (SELECT COUNT(*) FROM sys.dm_exec_query_stats);
        DECLARE @WarmthStatus  NVARCHAR(16);
        DECLARE @WarmthMessage NVARCHAR(MAX);
        IF @PlanCount = 0
        BEGIN
            SET @WarmthStatus  = N'INFO';
            SET @WarmthMessage = N'Plan cache is empty. Run representative workload before relying on TopCpu/TopDuration baselines.';
        END
        ELSE IF @PlanCount < 100
        BEGIN
            SET @WarmthStatus  = N'INFO';
            SET @WarmthMessage = N'Plan cache is cold (' + CAST(@PlanCount AS NVARCHAR(10))
                               + N' entries). Re-run after at least 1 hour of representative workload for meaningful baselines.';
        END
        ELSE
        BEGIN
            SET @WarmthStatus  = N'INFO';
            SET @WarmthMessage = N'Plan cache contains ' + CAST(@PlanCount AS NVARCHAR(10)) + N' entries.';
        END;

        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, ExpectedValue, ActualValue, Status, Details)
        VALUES
            (@RunId, N'Performance', N'PlanCacheWarmth',
             N'>= 100 entries for meaningful baseline',
             CAST(@PlanCount AS NVARCHAR(10)) + N' entries',
             @WarmthStatus, @WarmthMessage);
    END
    ELSE
    BEGIN
        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, Status, Details)
        VALUES
            (@RunId, N'Performance', N'PlanCacheWarmth', N'WARN',
             N'VIEW DATABASE STATE not granted; cannot read sys.dm_exec_query_stats. Grant the permission to capture plan-cache baselines.');
    END;

    -----------------------------------------------------------------------
    -- 2d. WaitStats
    -----------------------------------------------------------------------
    IF @HasVds = 1
    BEGIN
        DECLARE @TotalSignal BIGINT = (
            SELECT  ISNULL(SUM(signal_wait_time_ms), 0)
            FROM    sys.dm_db_wait_stats
            WHERE   wait_type NOT IN (
                N'BROKER_EVENTHANDLER', N'BROKER_RECEIVE_WAITFOR', N'BROKER_TASK_STOP',
                N'BROKER_TO_FLUSH', N'BROKER_TRANSMITTER', N'CHECKPOINT_QUEUE',
                N'CLR_AUTO_EVENT', N'CLR_MANUAL_EVENT', N'CLR_SEMAPHORE',
                N'DISPATCHER_QUEUE_SEMAPHORE', N'FT_IFTS_SCHEDULER_IDLE_WAIT',
                N'HADR_FILESTREAM_IOMGR_IOCOMPLETION', N'HADR_LOGCAPTURE_WAIT',
                N'HADR_NOTIFICATION_DEQUEUE', N'HADR_TIMER_TASK',
                N'HADR_WORK_QUEUE', N'KSOURCE_WAKEUP', N'LAZYWRITER_SLEEP',
                N'LOGMGR_QUEUE', N'ONDEMAND_TASK_QUEUE', N'PWAIT_ALL_COMPONENTS_INITIALIZED',
                N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP', N'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP',
                N'REQUEST_FOR_DEADLOCK_SEARCH', N'SLEEP_TASK', N'SP_SERVER_DIAGNOSTICS_SLEEP',
                N'SQLTRACE_BUFFER_FLUSH', N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP',
                N'WAITFOR', N'WAIT_XTP_OFFLINE_CKPT_NEW_LOG'
            )
        );

        INSERT dbo.ValidationResults
            (RunId, Category, ObjectName, CheckName,
             ExpectedValue, ActualValue, Status, Details)
        SELECT  TOP 20
                @RunId, N'Performance', w.wait_type, N'WaitStats',
                N'(observational)',
                CAST(w.wait_time_ms AS NVARCHAR(20)) + N' ms total; '
                + CAST(w.signal_wait_time_ms AS NVARCHAR(20)) + N' ms signal',
                CASE
                    WHEN w.wait_type LIKE N'PAGEIOLATCH_%'
                         AND @TotalSignal > 0
                         AND (w.signal_wait_time_ms * 100.0 / NULLIF(@TotalSignal,0)) > 10.0
                         THEN N'WARN'
                    ELSE N'INFO'
                END,
                N'waiting_tasks_count = ' + CAST(w.waiting_tasks_count AS NVARCHAR(20))
                + N'; signal_share% = '
                + CASE WHEN @TotalSignal > 0
                       THEN CAST(CAST(w.signal_wait_time_ms * 100.0 / @TotalSignal AS DECIMAL(5,2)) AS NVARCHAR(10))
                       ELSE N'n/a' END
        FROM    sys.dm_db_wait_stats AS w
        WHERE   w.wait_type NOT IN (
                    N'BROKER_EVENTHANDLER', N'BROKER_RECEIVE_WAITFOR', N'BROKER_TASK_STOP',
                    N'BROKER_TO_FLUSH', N'BROKER_TRANSMITTER', N'CHECKPOINT_QUEUE',
                    N'CLR_AUTO_EVENT', N'CLR_MANUAL_EVENT', N'CLR_SEMAPHORE',
                    N'DISPATCHER_QUEUE_SEMAPHORE', N'FT_IFTS_SCHEDULER_IDLE_WAIT',
                    N'HADR_FILESTREAM_IOMGR_IOCOMPLETION', N'HADR_LOGCAPTURE_WAIT',
                    N'HADR_NOTIFICATION_DEQUEUE', N'HADR_TIMER_TASK',
                    N'HADR_WORK_QUEUE', N'KSOURCE_WAKEUP', N'LAZYWRITER_SLEEP',
                    N'LOGMGR_QUEUE', N'ONDEMAND_TASK_QUEUE', N'PWAIT_ALL_COMPONENTS_INITIALIZED',
                    N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP', N'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP',
                    N'REQUEST_FOR_DEADLOCK_SEARCH', N'SLEEP_TASK', N'SP_SERVER_DIAGNOSTICS_SLEEP',
                    N'SQLTRACE_BUFFER_FLUSH', N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP',
                    N'WAITFOR', N'WAIT_XTP_OFFLINE_CKPT_NEW_LOG'
                )
        ORDER   BY w.wait_time_ms DESC;
    END
    ELSE
    BEGIN
        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, Status, Details)
        VALUES
            (@RunId, N'Performance', N'WaitStats', N'WARN',
             N'VIEW DATABASE STATE not granted; cannot read sys.dm_db_wait_stats.');
    END;

    -----------------------------------------------------------------------
    -- 2e. TopCpu / TopDuration  (scoped to mapped tables, capped to N)
    -----------------------------------------------------------------------
    IF @HasVds = 1
    BEGIN
        DECLARE @ScopeCount INT = (SELECT COUNT(*) FROM dbo.ValidationFkScopeTables);
        IF @ScopeCount > @MaxScopeForCache
        BEGIN
            INSERT dbo.ValidationResults
                (RunId, Category, CheckName, ExpectedValue, ActualValue, Status, Details)
            VALUES
                (@RunId, N'Performance', N'ScopeTruncated',
                 CAST(@MaxScopeForCache AS NVARCHAR(10)),
                 CAST(@ScopeCount AS NVARCHAR(10)),
                 N'INFO',
                 N'Mapped-table scope exceeds MaxScopeTablesForPlanCache; only the first '
                 + CAST(@MaxScopeForCache AS NVARCHAR(10))
                 + N' table(s) (by name) are scanned in TopCpu/TopDuration.');
        END;

        -- Build an OR-of-CHARINDEX predicate from the (capped) scope table.
        DECLARE @LikePredicate NVARCHAR(MAX) = N'';
        SELECT  @LikePredicate =
                STRING_AGG(
                    N'CHARINDEX(N''[' + s.TableName + N']'', st.text) > 0',
                    N' OR '
                )
        FROM    (SELECT TOP (@MaxScopeForCache) TableName
                 FROM   dbo.ValidationFkScopeTables
                 ORDER BY SchemaName, TableName) AS s;

        IF @LikePredicate IS NULL OR LEN(@LikePredicate) = 0
            SET @LikePredicate = N'1 = 0';

        DECLARE @TopCpuSql NVARCHAR(MAX) = N'
            INSERT dbo.ValidationResults
                (RunId, Category, CheckName, ObjectName,
                 ExpectedValue, ActualValue, Status, Details)
            SELECT TOP 20 @RunId, N''Performance'', N''TopCpu'',
                   LEFT(st.text, 256),
                   N''(observational)'',
                   CAST(qs.total_worker_time / 1000 AS NVARCHAR(20)) + N'' ms CPU'',
                   N''INFO'',
                   N''exec_count='' + CAST(qs.execution_count AS NVARCHAR(20))
                   + N''; avg_cpu_ms='' + CAST((qs.total_worker_time / NULLIF(qs.execution_count,0)) / 1000 AS NVARCHAR(20))
                   + N''; last_exec='' + CONVERT(NVARCHAR(30), qs.last_execution_time, 121)
            FROM   sys.dm_exec_query_stats AS qs
            CROSS  APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st
            WHERE  st.text IS NOT NULL
              AND  (' + @LikePredicate + N')
            ORDER  BY qs.total_worker_time DESC;';
        EXEC sp_executesql @TopCpuSql, N'@RunId UNIQUEIDENTIFIER', @RunId = @RunId;

        DECLARE @TopDurSql NVARCHAR(MAX) = N'
            INSERT dbo.ValidationResults
                (RunId, Category, CheckName, ObjectName,
                 ExpectedValue, ActualValue, Status, Details)
            SELECT TOP 20 @RunId, N''Performance'', N''TopDuration'',
                   LEFT(st.text, 256),
                   N''(observational)'',
                   CAST(qs.total_elapsed_time / 1000 AS NVARCHAR(20)) + N'' ms elapsed'',
                   N''INFO'',
                   N''exec_count='' + CAST(qs.execution_count AS NVARCHAR(20))
                   + N''; avg_ms='' + CAST((qs.total_elapsed_time / NULLIF(qs.execution_count,0)) / 1000 AS NVARCHAR(20))
                   + N''; last_exec='' + CONVERT(NVARCHAR(30), qs.last_execution_time, 121)
            FROM   sys.dm_exec_query_stats AS qs
            CROSS  APPLY sys.dm_exec_sql_text(qs.sql_handle) AS st
            WHERE  st.text IS NOT NULL
              AND  (' + @LikePredicate + N')
            ORDER  BY qs.total_elapsed_time DESC;';
        EXEC sp_executesql @TopDurSql, N'@RunId UNIQUEIDENTIFIER', @RunId = @RunId;
    END
    ELSE
    BEGIN
        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, Status, Details)
        VALUES
            (@RunId, N'Performance', N'TopCpu', N'WARN',
             N'VIEW DATABASE STATE not granted; skipping plan-cache scan.'),
            (@RunId, N'Performance', N'TopDuration', N'WARN',
             N'VIEW DATABASE STATE not granted; skipping plan-cache scan.');
    END;

    -----------------------------------------------------------------------
    -- 2f. MissingIndex (scoped to mapped tables)
    -----------------------------------------------------------------------
    IF @HasVds = 1
    BEGIN
        INSERT dbo.ValidationResults
            (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
             ExpectedValue, ActualValue, Status, Details)
        SELECT  @RunId, N'Performance',
                SCHEMA_NAME(o.schema_id), o.name, mid.equality_columns,
                N'MissingIndex',
                N'(observational)',
                CAST(CAST(migs.avg_total_user_cost * migs.avg_user_impact
                          * (migs.user_seeks + migs.user_scans) AS DECIMAL(18,2)) AS NVARCHAR(40)),
                CASE WHEN (migs.avg_total_user_cost * migs.avg_user_impact
                           * (migs.user_seeks + migs.user_scans)) > @MissingIndexWarn
                     THEN N'WARN' ELSE N'INFO' END,
                N'equality=[' + ISNULL(mid.equality_columns, N'') + N'] '
                + N'inequality=[' + ISNULL(mid.inequality_columns, N'') + N'] '
                + N'include=['   + ISNULL(mid.included_columns,   N'') + N']; '
                + N'seeks='      + CAST(migs.user_seeks AS NVARCHAR(20)) + N'; '
                + N'scans='      + CAST(migs.user_scans AS NVARCHAR(20)) + N'; '
                + N'avg_impact=' + CAST(CAST(migs.avg_user_impact AS DECIMAL(5,2)) AS NVARCHAR(10))
        FROM    sys.dm_db_missing_index_details   AS mid
        JOIN    sys.dm_db_missing_index_groups    AS mig  ON mig.index_handle = mid.index_handle
        JOIN    sys.dm_db_missing_index_group_stats AS migs ON migs.group_handle = mig.index_group_handle
        JOIN    sys.objects AS o ON o.object_id = mid.object_id
        JOIN    dbo.ValidationFkScopeTables AS sc
                ON  sc.SchemaName = SCHEMA_NAME(o.schema_id)
                AND sc.TableName  = o.name
        WHERE   mid.database_id = DB_ID();

        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, ExpectedValue, ActualValue, Status, Details)
        SELECT  @RunId, N'Performance', N'MissingIndexDmvAge',
                N'(observational)',
                CONVERT(NVARCHAR(30), sqlserver_start_time, 121),
                N'INFO',
                N'sys.dm_db_missing_index_* DMVs accumulate since the time above. '
                + N'Older snapshots are more reliable; treat suggestions cautiously '
                + N'if the start time is recent.'
        FROM    sys.dm_os_sys_info;
    END
    ELSE
    BEGIN
        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, Status, Details)
        VALUES
            (@RunId, N'Performance', N'MissingIndex', N'WARN',
             N'VIEW DATABASE STATE not granted; cannot read sys.dm_db_missing_index_*.');
    END;

    -----------------------------------------------------------------------
    -- 2g. StatsFreshness
    -----------------------------------------------------------------------
    IF @HasVds = 1
    BEGIN
        ;WITH row_counts AS (
            SELECT  object_id, SUM(row_count) AS RowCnt
            FROM    sys.dm_db_partition_stats
            WHERE   index_id IN (0, 1)
            GROUP BY object_id
        )
        INSERT dbo.ValidationResults
            (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
             ExpectedValue, ActualValue, Status, Details)
        SELECT  @RunId, N'Performance',
                sc.SchemaName, sc.TableName, s.name, N'StatsFreshness',
                N'STATS_DATE within 30 days for tables > 100k rows',
                COALESCE(CONVERT(NVARCHAR(30), STATS_DATE(s.object_id, s.stats_id), 121),
                         N'<never updated>'),
                CASE
                    WHEN STATS_DATE(s.object_id, s.stats_id) IS NULL
                         AND ISNULL(rc.RowCnt, 0) > 100000                  THEN N'WARN'
                    WHEN STATS_DATE(s.object_id, s.stats_id) IS NULL        THEN N'INFO'
                    WHEN DATEDIFF(DAY, STATS_DATE(s.object_id, s.stats_id), SYSUTCDATETIME()) > 30
                         AND ISNULL(rc.RowCnt, 0) > 100000                  THEN N'WARN'
                    ELSE                                                          N'INFO'
                END,
                N'row_count=' + CAST(ISNULL(rc.RowCnt, 0) AS NVARCHAR(20))
                + N'; age_days='
                + CASE WHEN STATS_DATE(s.object_id, s.stats_id) IS NULL THEN N'n/a'
                       ELSE CAST(DATEDIFF(DAY, STATS_DATE(s.object_id, s.stats_id), SYSUTCDATETIME()) AS NVARCHAR(10))
                  END
        FROM    sys.stats AS s
        JOIN    sys.tables AS t ON t.object_id = s.object_id
        JOIN    dbo.ValidationFkScopeTables AS sc
                ON  sc.SchemaName = SCHEMA_NAME(t.schema_id)
                AND sc.TableName  = t.name
        LEFT    JOIN row_counts AS rc ON rc.object_id = s.object_id
        WHERE   (s.auto_created = 1 OR s.user_created = 1);
    END
    ELSE
    BEGIN
        INSERT dbo.ValidationResults
            (RunId, Category, CheckName, Status, Details)
        VALUES
            (@RunId, N'Performance', N'StatsFreshness', N'WARN',
             N'VIEW DATABASE STATE not granted; cannot evaluate STATS_DATE.');
    END;

    -----------------------------------------------------------------------
    -- 2h. Summary
    -----------------------------------------------------------------------
    INSERT dbo.ValidationResults
        (RunId, Category, CheckName, ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Performance', N'Summary',
            CAST(COUNT(*) AS NVARCHAR(20)),
            CAST(SUM(CASE WHEN Status = N'WARN' THEN 1 ELSE 0 END) AS NVARCHAR(20)) + N' warning(s)',
            CASE WHEN SUM(CASE WHEN Status = N'WARN' THEN 1 ELSE 0 END) > 0
                 THEN N'WARN' ELSE N'INFO' END,
            CAST(COUNT(*) AS NVARCHAR(20)) + N' performance baseline row(s) captured; '
            + CAST(SUM(CASE WHEN Status = N'WARN' THEN 1 ELSE 0 END) AS NVARCHAR(20))
            + N' warning(s).'
    FROM    dbo.ValidationResults
    WHERE   RunId = @RunId
      AND   Category = N'Performance'
      AND   CheckName <> N'Summary';
END;
GO
