/*
================================================================================
 05-IndexValidation.sql
 Generated by Cosmos-to-SQL Migration Assessment Tool

 Purpose
   Post-migration index validation. For every index recommended by the
   assessment:
     1. Existence    -- index exists in sys.indexes (matched by schema/table/name).
     2. Enabled      -- is_disabled = 0 (emit ALTER INDEX ... REBUILD hint otherwise).
     3. Type         -- type_desc matches (with COLUMNSTORE tolerance).
     4. Uniqueness   -- is_unique matches (skipped for COLUMNSTORE actual).
     5. Key columns  -- ordered, case-insensitive comma-joined match.
     6. Included     -- ordered, case-insensitive match (drift = WARN, not FAIL).
     7. Filter       -- actual has a filter but expected does not (WARN).

   Plus a discovery sweep that surfaces "unexpected" physical indexes -- any
   index in sys.indexes on a mapped table that is NOT in the assessment.
   PRIMARY KEYs, HEAPs, and hypothetical indexes are filtered to avoid noise.

 Output
   One row per expected index in dbo.ValidationResults
   (Category = N'Index', CheckName = N'Definition').
   Optional INFO rows for unexpected indexes (CheckName = N'Unexpected').

 Required permissions
   - VIEW DEFINITION on sys.indexes (default for db_datareader+).

 Re-use
   Re-uses dbo.ValidationFkScopeTables (created by 06-ForeignKeyValidation.sql)
   to scope the "unexpected index" sweep to assessment-mapped tables only.
   Run 06 first, or this script will create the scope table if needed.

 NOTE on COLUMNSTORE
   Assessment's IndexType = "ColumnStore" is rendered here as expected
   type NONCLUSTERED COLUMNSTORE. The comparison treats CLUSTERED COLUMNSTORE
   actual as also matching expected ColumnStore (different code paths in
   SqlProjectGenerationService vs SqlDatabaseProjectService may emit either).
================================================================================
*/

:setvar RunId "00000000-0000-0000-0000-000000000000"
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-------------------------------------------------------------------------------
-- 1. Seed tables.
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationExpectedIndexes', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationExpectedIndexes
    (
        SchemaName       NVARCHAR(128) NOT NULL,
        TableName        NVARCHAR(128) NOT NULL,
        IndexName        NVARCHAR(128) NOT NULL,
        ExpectedType     NVARCHAR(64)  NOT NULL,
        IsUnique         BIT           NOT NULL,
        KeyColumns       NVARCHAR(MAX) NOT NULL,
        IncludedColumns  NVARCHAR(MAX) NOT NULL,
        CapturedAt       DATETIME2(3)  NOT NULL
            CONSTRAINT DF_VExpIdx_CapturedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_ValidationExpectedIndexes
            PRIMARY KEY (SchemaName, TableName, IndexName)
    );
END;
GO

-- Re-create the scope table if 06-ForeignKeyValidation.sql has not run.
-- Keeps this script independently runnable.
IF OBJECT_ID(N'dbo.ValidationFkScopeTables', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationFkScopeTables
    (
        SchemaName NVARCHAR(128) NOT NULL,
        TableName  NVARCHAR(128) NOT NULL,
        CONSTRAINT PK_ValidationFkScopeTables PRIMARY KEY (SchemaName, TableName)
    );
END;
GO

-------------------------------------------------------------------------------
-- 2. Main validation batch.
-------------------------------------------------------------------------------
BEGIN
    DECLARE @RunId UNIQUEIDENTIFIER = TRY_CAST(N'$(RunId)' AS UNIQUEIDENTIFIER);
    IF @RunId IS NULL OR @RunId = CAST(N'00000000-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
    BEGIN
        SET @RunId = NEWID();
        PRINT N'WARNING: No orchestrator RunId supplied; generated local RunId = '
              + CONVERT(NVARCHAR(36), @RunId)
              + N'. Standalone run -- results will not appear in the cross-script report.';
    END;

    -- {{ExpectedIndexesSeed}}
{{ExpectedIndexesSeed}}

    -- {{ScopeTablesSeed}}
{{ScopeTablesSeed}}

    -------------------------------------------------------------------------
    -- 2a. Discover actual indexes on mapped tables.
    --     STRING_AGG produces order-significant comma-joined lists.
    --     Key columns are ordered by key_ordinal (1-based position in key).
    --     Included columns are ordered by index_column_id (stable absolute
    --     position in the index column list) since key_ordinal = 0 for them.
    -------------------------------------------------------------------------
    ;WITH index_cols AS (
        SELECT  i.object_id,
                i.index_id,
                ic.is_included_column,
                ic.key_ordinal,
                ic.index_column_id,
                c.name AS ColumnName
        FROM    sys.indexes        AS i
        JOIN    sys.index_columns  AS ic ON ic.object_id = i.object_id
                                         AND ic.index_id  = i.index_id
        JOIN    sys.columns        AS c  ON c.object_id  = ic.object_id
                                         AND c.column_id = ic.column_id
    ),
    discovered AS (
        SELECT  i.object_id,
                i.index_id,
                i.name                                       AS IndexName,
                SCHEMA_NAME(t.schema_id)                     AS SchemaName,
                t.name                                       AS TableName,
                i.type_desc                                  AS ActualType,
                i.is_unique                                  AS IsUnique,
                i.is_disabled                                AS IsDisabled,
                i.is_primary_key                             AS IsPrimaryKey,
                i.is_hypothetical                            AS IsHypothetical,
                CASE WHEN i.filter_definition IS NULL
                     THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END AS HasFilter,
                i.filter_definition                          AS FilterDefinition,
                ISNULL((
                    SELECT STRING_AGG(CAST(kc.ColumnName AS NVARCHAR(MAX)), N', ')
                           WITHIN GROUP (ORDER BY kc.key_ordinal)
                    FROM   index_cols AS kc
                    WHERE  kc.object_id = i.object_id
                      AND  kc.index_id  = i.index_id
                      AND  kc.is_included_column = 0
                ), N'')                                      AS ActualKeyColumns,
                ISNULL((
                    SELECT STRING_AGG(CAST(ic2.ColumnName AS NVARCHAR(MAX)), N', ')
                           WITHIN GROUP (ORDER BY ic2.index_column_id)
                    FROM   index_cols AS ic2
                    WHERE  ic2.object_id = i.object_id
                      AND  ic2.index_id  = i.index_id
                      AND  ic2.is_included_column = 1
                ), N'')                                      AS ActualIncludedColumns
        FROM    sys.indexes AS i
        JOIN    sys.tables  AS t ON t.object_id = i.object_id
        WHERE   i.type_desc      <> N'HEAP'
          AND   i.is_hypothetical = 0
          AND   i.name IS NOT NULL  -- HEAPs already excluded but defensive
    )
    -------------------------------------------------------------------------
    -- 2b. Expected -> Actual comparison.
    -------------------------------------------------------------------------
    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Index',
            e.SchemaName, e.TableName, e.IndexName, N'Definition',
            e.ExpectedType + N' (Unique=' + CAST(e.IsUnique AS NVARCHAR(1))
                + N') keys=[' + e.KeyColumns
                + N'] include=[' + e.IncludedColumns + N']',
            COALESCE(
                d.ActualType + N' (Unique=' + CAST(d.IsUnique AS NVARCHAR(1))
                    + N') keys=[' + d.ActualKeyColumns
                    + N'] include=[' + d.ActualIncludedColumns + N']',
                N'<missing>'),
            CASE
                WHEN d.object_id IS NULL                                   THEN N'FAIL'
                WHEN d.IsDisabled = 1                                      THEN N'FAIL'
                WHEN NOT (
                        d.ActualType = e.ExpectedType
                        OR (e.ExpectedType LIKE N'%COLUMNSTORE%'
                            AND d.ActualType LIKE N'%COLUMNSTORE%')
                     )                                                     THEN N'FAIL'
                WHEN d.ActualType NOT LIKE N'%COLUMNSTORE%'
                     AND d.IsUnique <> e.IsUnique                          THEN N'FAIL'
                WHEN d.ActualKeyColumns COLLATE Latin1_General_CI_AS
                     <> e.KeyColumns    COLLATE Latin1_General_CI_AS       THEN N'FAIL'
                WHEN d.ActualIncludedColumns COLLATE Latin1_General_CI_AS
                     <> e.IncludedColumns    COLLATE Latin1_General_CI_AS  THEN N'WARN'
                WHEN d.HasFilter = 1                                       THEN N'WARN'
                ELSE                                                            N'PASS'
            END,
            CASE
                WHEN d.object_id IS NULL THEN
                    N'Index [' + e.IndexName + N'] not found on '
                    + QUOTENAME(e.SchemaName) + N'.' + QUOTENAME(e.TableName) + N'.'
                WHEN d.IsDisabled = 1 THEN
                    N'Index is disabled. Remediation: ALTER INDEX '
                    + QUOTENAME(d.IndexName) + N' ON '
                    + QUOTENAME(e.SchemaName) + N'.' + QUOTENAME(e.TableName)
                    + N' REBUILD;'
                WHEN NOT (
                        d.ActualType = e.ExpectedType
                        OR (e.ExpectedType LIKE N'%COLUMNSTORE%'
                            AND d.ActualType LIKE N'%COLUMNSTORE%')
                     ) THEN
                    N'Index type mismatch: expected ' + e.ExpectedType
                    + N'; actual ' + d.ActualType + N'.'
                WHEN d.ActualType NOT LIKE N'%COLUMNSTORE%'
                     AND d.IsUnique <> e.IsUnique THEN
                    N'Uniqueness mismatch: expected is_unique = '
                    + CAST(e.IsUnique AS NVARCHAR(1))
                    + N'; actual = ' + CAST(d.IsUnique AS NVARCHAR(1)) + N'.'
                WHEN d.ActualKeyColumns COLLATE Latin1_General_CI_AS
                     <> e.KeyColumns    COLLATE Latin1_General_CI_AS THEN
                    N'Key column drift: expected [' + e.KeyColumns
                    + N']; actual [' + d.ActualKeyColumns + N'].'
                WHEN d.ActualIncludedColumns COLLATE Latin1_General_CI_AS
                     <> e.IncludedColumns    COLLATE Latin1_General_CI_AS THEN
                    N'Included column drift: expected [' + e.IncludedColumns
                    + N']; actual [' + d.ActualIncludedColumns + N'].'
                WHEN d.HasFilter = 1 THEN
                    N'Actual index has filter [' + d.FilterDefinition
                    + N'] but expected has no filter. Verify intent.'
                ELSE
                    N'Index matches assessment (type, uniqueness, key + include columns).'
            END
    FROM    dbo.ValidationExpectedIndexes AS e
    LEFT    JOIN discovered                AS d
            ON  d.SchemaName = e.SchemaName
            AND d.TableName  = e.TableName
            AND d.IndexName  = e.IndexName;

    -------------------------------------------------------------------------
    -- 2c. Unexpected-index discovery (INFO rows only).
    --     Scoped to mapped tables. Excludes PKs, HEAPs, hypothetical, and
    --     anything already in the expected list.
    -------------------------------------------------------------------------
    ;WITH unexpected AS (
        SELECT  SCHEMA_NAME(t.schema_id) AS SchemaName,
                t.name                   AS TableName,
                i.name                   AS IndexName,
                i.type_desc              AS ActualType,
                i.is_unique              AS IsUnique
        FROM    sys.indexes AS i
        JOIN    sys.tables  AS t ON t.object_id = i.object_id
        JOIN    dbo.ValidationFkScopeTables AS sc
                ON  sc.SchemaName = SCHEMA_NAME(t.schema_id)
                AND sc.TableName  = t.name
        WHERE   i.type_desc      <> N'HEAP'
          AND   i.is_hypothetical = 0
          AND   i.is_primary_key  = 0
          AND   i.name IS NOT NULL
    )
    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Index',
            u.SchemaName, u.TableName, u.IndexName, N'Unexpected',
            N'(not in assessment)',
            u.ActualType + N' (Unique=' + CAST(u.IsUnique AS NVARCHAR(1)) + N')',
            N'INFO',
            N'Physical index present on mapped table but not in assessment recommendations. '
            + N'Review whether it is intentional (manual tuning, vendor add) or stale (leftover from prior schema).'
    FROM    unexpected AS u
    LEFT    JOIN dbo.ValidationExpectedIndexes AS e
            ON  e.SchemaName = u.SchemaName
            AND e.TableName  = u.TableName
            AND e.IndexName  = u.IndexName
    WHERE   e.IndexName IS NULL;

    -------------------------------------------------------------------------
    -- 2d. Summary row.
    -------------------------------------------------------------------------
    INSERT dbo.ValidationResults
        (RunId, Category, CheckName, ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'Index', N'Summary',
            CAST(COUNT(*) AS NVARCHAR(20)),
            CAST(SUM(CASE WHEN Status = N'PASS' THEN 1 ELSE 0 END) AS NVARCHAR(20)),
            CASE
                WHEN SUM(CASE WHEN Status = N'FAIL' THEN 1 ELSE 0 END) > 0 THEN N'FAIL'
                WHEN SUM(CASE WHEN Status = N'WARN' THEN 1 ELSE 0 END) > 0 THEN N'WARN'
                ELSE N'PASS'
            END,
            CAST(SUM(CASE WHEN Status = N'PASS' THEN 1 ELSE 0 END) AS NVARCHAR(20))
            + N' / ' + CAST(COUNT(*) AS NVARCHAR(20))
            + N' index check(s) passed; '
            + CAST(SUM(CASE WHEN Status = N'WARN' THEN 1 ELSE 0 END) AS NVARCHAR(20))
            + N' warning(s); '
            + CAST(SUM(CASE WHEN Status = N'FAIL' THEN 1 ELSE 0 END) AS NVARCHAR(20))
            + N' failure(s).'
    FROM    dbo.ValidationResults
    WHERE   RunId = @RunId
      AND   Category = N'Index'
      AND   CheckName <> N'Summary';
END;
GO
