/*
================================================================================
 06-ForeignKeyValidation.sql
 Generated by Cosmos-to-SQL Migration Assessment Tool

 Purpose
   Post-migration referential-integrity harness. Three checks per FK:
     1. Existence  -- every assessment-listed FK exists in sys.foreign_keys.
     2. Trust      -- is_not_trusted = 0 (post-bulk-import FKs are often
                      untrusted and the optimizer ignores them).
     3. Orphans    -- per-FK NULL-safe NOT EXISTS scan, including composites.

 Scope guard
   Only FKs whose child AND parent tables appear in the assessment's
   ContainerMappings are scanned. Out-of-scope FKs are summarised as a
   single INFO row so the report shows the gap without scanning unrelated
   500M-row tables.

 Throttle
   :setvar MaxOrphanScanRows "10000000"
   Child tables exceeding this row count (per sys.dm_db_partition_stats)
   are skipped with an INFO row -- the operator can lower or override.

 Required permissions
   - SELECT on every target schema/table.
   - VIEW DEFINITION on sys.foreign_keys (default for db_datareader+).
================================================================================
*/

:setvar RunId             "00000000-0000-0000-0000-000000000000"
:setvar MaxOrphanScanRows "10000000"
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

-------------------------------------------------------------------------------
-- 1. Seed tables.
-------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ValidationExpectedForeignKeys', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationExpectedForeignKeys
    (
        FkName         SYSNAME       NOT NULL
            CONSTRAINT PK_ValidationExpectedForeignKeys PRIMARY KEY,
        ChildSchema    NVARCHAR(128) NOT NULL,
        ChildTable     NVARCHAR(128) NOT NULL,
        ChildColumn    NVARCHAR(128) NOT NULL,
        ParentSchema   NVARCHAR(128) NOT NULL,
        ParentTable    NVARCHAR(128) NOT NULL,
        ParentColumn   NVARCHAR(128) NOT NULL,
        OnDeleteAction NVARCHAR(20)  NOT NULL,
        OnUpdateAction NVARCHAR(20)  NOT NULL,
        CapturedAt     DATETIME2(3)  NOT NULL
            CONSTRAINT DF_VExpFk_CapturedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID(N'dbo.ValidationFkScopeTables', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationFkScopeTables
    (
        SchemaName NVARCHAR(128) NOT NULL,
        TableName  NVARCHAR(128) NOT NULL,
        CONSTRAINT PK_ValidationFkScopeTables PRIMARY KEY (SchemaName, TableName)
    );
END;
GO

-------------------------------------------------------------------------------
-- 2. Reusable orphan-check procedure (per FK).
-------------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE dbo.sp_ValidationForeignKeyOrphans
    @RunId             UNIQUEIDENTIFIER,
    @FkObjectId        INT,
    @MaxOrphanScanRows BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @FkName        SYSNAME,
            @ChildSchema   NVARCHAR(128),
            @ChildTable    NVARCHAR(128),
            @ParentSchema  NVARCHAR(128),
            @ParentTable   NVARCHAR(128),
            @ChildObjectId INT;

    SELECT  @FkName        = fk.name,
            @ChildSchema   = SCHEMA_NAME(ct.schema_id),
            @ChildTable    = ct.name,
            @ChildObjectId = ct.object_id,
            @ParentSchema  = SCHEMA_NAME(pt.schema_id),
            @ParentTable   = pt.name
    FROM    sys.foreign_keys AS fk
    JOIN    sys.tables       AS ct ON ct.object_id = fk.parent_object_id
    JOIN    sys.tables       AS pt ON pt.object_id = fk.referenced_object_id
    WHERE   fk.object_id = @FkObjectId;

    IF @FkName IS NULL
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, CheckName, Status, Details)
        VALUES (@RunId, N'ForeignKey', N'OrphanScan', N'FAIL',
                N'FK object_id ' + CAST(@FkObjectId AS NVARCHAR(20))
                + N' not found in sys.foreign_keys.');
        RETURN;
    END;

    DECLARE @ChildFullName  NVARCHAR(260) = QUOTENAME(@ChildSchema)  + N'.' + QUOTENAME(@ChildTable);
    DECLARE @ParentFullName NVARCHAR(260) = QUOTENAME(@ParentSchema) + N'.' + QUOTENAME(@ParentTable);

    -- Pre-flight row-count throttle.
    DECLARE @ChildRows BIGINT =
    (
        SELECT  SUM(row_count)
        FROM    sys.dm_db_partition_stats
        WHERE   object_id = @ChildObjectId
            AND index_id IN (0, 1)
    );

    IF @ChildRows IS NULL
        SET @ChildRows = 0;

    IF @ChildRows > @MaxOrphanScanRows
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, ObjectName, CheckName, Status, Details)
        VALUES (@RunId, N'ForeignKey', @ChildSchema, @ChildTable, @FkName, N'OrphanScan', N'INFO',
                N'Orphan scan skipped: child table row count ' + CAST(@ChildRows AS NVARCHAR(20))
                + N' exceeds MaxOrphanScanRows ' + CAST(@MaxOrphanScanRows AS NVARCHAR(20))
                + N'. Tune :setvar MaxOrphanScanRows to opt in.');
        RETURN;
    END;

    -- Build NULL-safe composite predicate from sys.foreign_key_columns.
    DECLARE @NullGuard NVARCHAR(MAX) = N'';
    DECLARE @JoinPred  NVARCHAR(MAX) = N'';

    SELECT  @NullGuard = STRING_AGG(N'c.' + QUOTENAME(cc.name) + N' IS NOT NULL', N' AND ')
                            WITHIN GROUP (ORDER BY fkc.constraint_column_id),
            @JoinPred  = STRING_AGG(N'p.' + QUOTENAME(pc.name) + N' = c.' + QUOTENAME(cc.name), N' AND ')
                            WITHIN GROUP (ORDER BY fkc.constraint_column_id)
    FROM    sys.foreign_key_columns AS fkc
    JOIN    sys.columns AS cc ON cc.object_id = fkc.parent_object_id AND cc.column_id = fkc.parent_column_id
    JOIN    sys.columns AS pc ON pc.object_id = fkc.referenced_object_id AND pc.column_id = fkc.referenced_column_id
    WHERE   fkc.constraint_object_id = @FkObjectId;

    IF @NullGuard IS NULL OR @JoinPred IS NULL
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, ObjectName, CheckName, Status, Details)
        VALUES (@RunId, N'ForeignKey', @ChildSchema, @ChildTable, @FkName, N'OrphanScan', N'FAIL',
                N'No columns found in sys.foreign_key_columns for FK ' + @FkName + N'.');
        RETURN;
    END;

    DECLARE @Sql NVARCHAR(MAX) = N'
        SELECT @Orphans = COUNT_BIG(*)
        FROM   ' + @ChildFullName + N' AS c WITH (NOLOCK)
        WHERE  ' + @NullGuard + N'
          AND NOT EXISTS (
                SELECT 1
                FROM   ' + @ParentFullName + N' AS p WITH (NOLOCK)
                WHERE  ' + @JoinPred + N'
          );';

    DECLARE @Orphans BIGINT = 0;
    BEGIN TRY
        EXEC sys.sp_executesql @Sql, N'@Orphans BIGINT OUTPUT', @Orphans = @Orphans OUTPUT;
    END TRY
    BEGIN CATCH
        INSERT dbo.ValidationResults (RunId, Category, SchemaName, TableName, ObjectName, CheckName, Status, Details)
        VALUES (@RunId, N'ForeignKey', @ChildSchema, @ChildTable, @FkName, N'OrphanScan', N'FAIL',
                N'Error running orphan scan for ' + @FkName + N': ' + ERROR_MESSAGE());
        RETURN;
    END CATCH;

    DECLARE @Status  NVARCHAR(16);
    DECLARE @Details NVARCHAR(MAX);
    IF @Orphans = 0
    BEGIN
        SET @Status  = N'PASS';
        SET @Details = N'No orphan rows in ' + @ChildFullName + N' (scanned '
                     + CAST(@ChildRows AS NVARCHAR(20)) + N' row(s)).';
    END
    ELSE
    BEGIN
        SET @Status  = N'FAIL';
        SET @Details = CAST(@Orphans AS NVARCHAR(20)) + N' orphan row(s) detected in '
                     + @ChildFullName + N' referencing missing parent in '
                     + @ParentFullName + N'.';
    END;

    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    VALUES
        (@RunId, N'ForeignKey', @ChildSchema, @ChildTable, @FkName, N'OrphanScan',
         N'0', CAST(@Orphans AS NVARCHAR(20)), @Status, @Details);
END;
GO

-------------------------------------------------------------------------------
-- 3. Main validation batch.
-------------------------------------------------------------------------------
BEGIN
    DECLARE @RunId UNIQUEIDENTIFIER = TRY_CAST(N'$(RunId)' AS UNIQUEIDENTIFIER);
    IF @RunId IS NULL OR @RunId = CAST(N'00000000-0000-0000-0000-000000000000' AS UNIQUEIDENTIFIER)
    BEGIN
        SET @RunId = NEWID();
        PRINT N'WARNING: No orchestrator RunId supplied; generated local RunId = '
              + CONVERT(NVARCHAR(36), @RunId)
              + N'. Standalone run -- results will not appear in the cross-script report.';
    END;

    DECLARE @MaxOrphanScanRows BIGINT = ISNULL(TRY_CAST(N'$(MaxOrphanScanRows)' AS BIGINT), 10000000);

    -- {{ExpectedForeignKeysSeed}}
{{ExpectedForeignKeysSeed}}

    -- {{FkScopeTablesSeed}}
{{FkScopeTablesSeed}}

    -------------------------------------------------------------------------
    -- 3a. Existence + column-shape + trust + cascade-action checks.
    -------------------------------------------------------------------------
    ;WITH discovered AS (
        SELECT  fk.object_id                  AS FkObjectId,
                fk.name                       AS FkName,
                SCHEMA_NAME(ct.schema_id)     AS ChildSchema,
                ct.name                       AS ChildTable,
                cc.name                       AS ChildColumn,
                SCHEMA_NAME(pt.schema_id)     AS ParentSchema,
                pt.name                       AS ParentTable,
                pc.name                       AS ParentColumn,
                fk.is_not_trusted             AS IsNotTrusted,
                fk.delete_referential_action_desc AS OnDeleteAction,
                fk.update_referential_action_desc AS OnUpdateAction,
                ROW_NUMBER() OVER (PARTITION BY fk.object_id
                                   ORDER BY fkc.constraint_column_id) AS ColPosition,
                COUNT(*) OVER (PARTITION BY fk.object_id)              AS ColCount
        FROM    sys.foreign_keys        AS fk
        JOIN    sys.foreign_key_columns AS fkc ON fkc.constraint_object_id = fk.object_id
        JOIN    sys.tables              AS ct  ON ct.object_id  = fk.parent_object_id
        JOIN    sys.tables              AS pt  ON pt.object_id  = fk.referenced_object_id
        JOIN    sys.columns             AS cc  ON cc.object_id  = fkc.parent_object_id
                                              AND cc.column_id  = fkc.parent_column_id
        JOIN    sys.columns             AS pc  ON pc.object_id  = fkc.referenced_object_id
                                              AND pc.column_id  = fkc.referenced_column_id
    ),
    -- Map cascade-action enum to short tokens for comparison with the assessment.
    discovered_norm AS (
        SELECT  d.*,
                REPLACE(d.OnDeleteAction, N'_', N' ') AS OnDeleteActionNorm,
                REPLACE(d.OnUpdateAction, N'_', N' ') AS OnUpdateActionNorm
        FROM    discovered AS d
    )
    INSERT dbo.ValidationResults
        (RunId, Category, SchemaName, TableName, ObjectName, CheckName,
         ExpectedValue, ActualValue, Status, Details)
    SELECT  @RunId, N'ForeignKey',
            e.ChildSchema, e.ChildTable, e.FkName, N'Definition',
            e.ChildSchema + N'.' + e.ChildTable + N'.' + e.ChildColumn
            + N' -> ' + e.ParentSchema + N'.' + e.ParentTable + N'.' + e.ParentColumn,
            COALESCE(d.ChildSchema + N'.' + d.ChildTable + N'.' + d.ChildColumn
                     + N' -> ' + d.ParentSchema + N'.' + d.ParentTable + N'.' + d.ParentColumn,
                     N'<missing>'),
            CASE
                WHEN d.FkObjectId IS NULL                          THEN N'FAIL'
                WHEN d.ColCount   <> 1                             THEN N'WARN'  -- composite: assessment only models single-col
                WHEN d.ChildSchema  <> e.ChildSchema
                  OR d.ChildTable   <> e.ChildTable
                  OR d.ChildColumn  <> e.ChildColumn
                  OR d.ParentSchema <> e.ParentSchema
                  OR d.ParentTable  <> e.ParentTable
                  OR d.ParentColumn <> e.ParentColumn              THEN N'FAIL'
                WHEN d.IsNotTrusted = 1                            THEN N'WARN'
                WHEN d.OnDeleteActionNorm <> e.OnDeleteAction
                  OR d.OnUpdateActionNorm <> e.OnUpdateAction      THEN N'WARN'
                ELSE                                                    N'PASS'
            END,
            CASE
                WHEN d.FkObjectId IS NULL THEN
                    N'FK [' + e.FkName + N'] not found in sys.foreign_keys.'
                WHEN d.ColCount <> 1 THEN
                    N'FK is composite (' + CAST(d.ColCount AS NVARCHAR(10))
                    + N' cols); assessment only models single-column FKs. Manual verification recommended.'
                WHEN d.ChildSchema  <> e.ChildSchema
                  OR d.ChildTable   <> e.ChildTable
                  OR d.ChildColumn  <> e.ChildColumn
                  OR d.ParentSchema <> e.ParentSchema
                  OR d.ParentTable  <> e.ParentTable
                  OR d.ParentColumn <> e.ParentColumn THEN
                    N'FK shape drift: expected '
                    + e.ChildSchema + N'.' + e.ChildTable + N'.' + e.ChildColumn
                    + N' -> ' + e.ParentSchema + N'.' + e.ParentTable + N'.' + e.ParentColumn
                    + N'; actual ' + d.ChildSchema + N'.' + d.ChildTable + N'.' + d.ChildColumn
                    + N' -> ' + d.ParentSchema + N'.' + d.ParentTable + N'.' + d.ParentColumn
                WHEN d.IsNotTrusted = 1 THEN
                    N'FK is not trusted. Remediation: ALTER TABLE '
                    + QUOTENAME(d.ChildSchema) + N'.' + QUOTENAME(d.ChildTable)
                    + N' WITH CHECK CHECK CONSTRAINT ' + QUOTENAME(d.FkName) + N';'
                WHEN d.OnDeleteActionNorm <> e.OnDeleteAction
                  OR d.OnUpdateActionNorm <> e.OnUpdateAction THEN
                    N'Cascade-action mismatch: expected ON DELETE ' + e.OnDeleteAction
                    + N' / ON UPDATE ' + e.OnUpdateAction
                    + N'; actual ON DELETE ' + d.OnDeleteActionNorm
                    + N' / ON UPDATE ' + d.OnUpdateActionNorm
                ELSE
                    N'FK definition matches assessment, is trusted, and cascade actions agree.'
            END
    FROM    dbo.ValidationExpectedForeignKeys AS e
    LEFT    JOIN discovered_norm AS d
            ON  d.FkName = e.FkName
            AND d.ColPosition = 1;     -- single representative row per FK

    -------------------------------------------------------------------------
    -- 3b. Per-FK orphan scan (scope-limited).
    -------------------------------------------------------------------------
    DECLARE @InScopeFks TABLE (FkObjectId INT PRIMARY KEY);
    INSERT @InScopeFks (FkObjectId)
    SELECT  fk.object_id
    FROM    sys.foreign_keys AS fk
    JOIN    sys.tables       AS ct ON ct.object_id = fk.parent_object_id
    JOIN    sys.tables       AS pt ON pt.object_id = fk.referenced_object_id
    JOIN    dbo.ValidationFkScopeTables AS sc
            ON sc.SchemaName = SCHEMA_NAME(ct.schema_id) AND sc.TableName = ct.name
    JOIN    dbo.ValidationFkScopeTables AS sp
            ON sp.SchemaName = SCHEMA_NAME(pt.schema_id) AND sp.TableName = pt.name;

    -- Out-of-scope FK summary.
    DECLARE @OutOfScopeNames NVARCHAR(MAX) = NULL;
    SELECT  @OutOfScopeNames = STRING_AGG(fk.name, N', ') WITHIN GROUP (ORDER BY fk.name)
    FROM    sys.foreign_keys AS fk
    WHERE   fk.object_id NOT IN (SELECT FkObjectId FROM @InScopeFks);

    IF @OutOfScopeNames IS NOT NULL
    BEGIN
        INSERT dbo.ValidationResults (RunId, Category, CheckName, Status, Details)
        VALUES (@RunId, N'ForeignKey', N'OutOfScopeFks', N'INFO',
                N'FKs in the database but outside the assessment scope (not scanned): '
                + @OutOfScopeNames);
    END;

    DECLARE @FkObjectId INT;
    DECLARE fk_cursor CURSOR LOCAL FAST_FORWARD FOR
        SELECT FkObjectId FROM @InScopeFks;

    OPEN fk_cursor;
    FETCH NEXT FROM fk_cursor INTO @FkObjectId;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        BEGIN TRY
            EXEC dbo.sp_ValidationForeignKeyOrphans
                @RunId             = @RunId,
                @FkObjectId        = @FkObjectId,
                @MaxOrphanScanRows = @MaxOrphanScanRows;
        END TRY
        BEGIN CATCH
            INSERT dbo.ValidationResults (RunId, Category, CheckName, Status, Details)
            VALUES (@RunId, N'ForeignKey', N'OrphanScan', N'FAIL',
                    N'Unhandled error scanning FK object_id ' + CAST(@FkObjectId AS NVARCHAR(20))
                    + N': ' + ERROR_MESSAGE());
        END CATCH;
        FETCH NEXT FROM fk_cursor INTO @FkObjectId;
    END;
    CLOSE fk_cursor;
    DEALLOCATE fk_cursor;

    DECLARE @Pass INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'ForeignKey' AND Status = N'PASS');
    DECLARE @Warn INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'ForeignKey' AND Status = N'WARN');
    DECLARE @Fail INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'ForeignKey' AND Status = N'FAIL');
    DECLARE @Info INT = (SELECT COUNT(*) FROM dbo.ValidationResults WHERE RunId = @RunId AND Category = N'ForeignKey' AND Status = N'INFO');
    PRINT N'[ForeignKey] RunId=' + CONVERT(NVARCHAR(36), @RunId)
        + N' Pass=' + CAST(@Pass AS NVARCHAR(20))
        + N' Warn=' + CAST(@Warn AS NVARCHAR(20))
        + N' Fail=' + CAST(@Fail AS NVARCHAR(20))
        + N' Info=' + CAST(@Info AS NVARCHAR(20));
END;
GO
