-- ============================================================
-- Custom database-scoped role for sqlpackage publish deployments
-- of the SQL Database Project generated by CosmosToSqlAssessment.
--
-- Use this role for STEADY-STATE schema-evolution deploys (adding
-- tables/views/procedures, altering columns, etc.).
--
-- For the FIRST/BOOTSTRAP deploy of a fresh DACPAC against an
-- empty database -- or any deploy that creates users, logins,
-- roles, permissions, or extended properties -- elevate the
-- deploying principal to db_owner temporarily, run sqlpackage,
-- then revoke db_owner and add to db_schema_deployer.
--
-- See docs/security/rbac/README.md for the full escalation matrix.
-- ============================================================

-- Run this script in the target database (NOT master) as a
-- principal that already holds db_owner or CONTROL on the database.

-- 1. Create the role if it does not already exist.
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'db_schema_deployer' AND type = N'R')
BEGIN
    CREATE ROLE db_schema_deployer;
END
GO

-- 2. Grant the minimum DDL surface for steady-state schema deploys.
GRANT ALTER ANY SCHEMA          TO db_schema_deployer;
GRANT ALTER ANY USER            TO db_schema_deployer;
GRANT CREATE TABLE              TO db_schema_deployer;
GRANT CREATE VIEW               TO db_schema_deployer;
GRANT CREATE PROCEDURE          TO db_schema_deployer;
GRANT CREATE FUNCTION           TO db_schema_deployer;
GRANT CREATE TYPE               TO db_schema_deployer;
GRANT VIEW DEFINITION           TO db_schema_deployer;
GRANT VIEW DATABASE STATE       TO db_schema_deployer;
GRANT ALTER ON SCHEMA::dbo      TO db_schema_deployer;
GRANT CONTROL ON SCHEMA::dbo    TO db_schema_deployer;

-- If your DACPAC adds DML (e.g., post-deployment seed scripts),
-- also grant INSERT / UPDATE / DELETE on the relevant schema.
-- GRANT INSERT, UPDATE, DELETE ON SCHEMA::dbo TO db_schema_deployer;
GO

-- 3. Create the deploying principal as a Microsoft Entra user
--    in this database and add to the role. REPLACE the placeholder.
--
-- For a Microsoft Entra group (recommended for CI/CD pipelines):
--   CREATE USER [sg-sql-deployers] FROM EXTERNAL PROVIDER;
--   ALTER ROLE db_schema_deployer ADD MEMBER [sg-sql-deployers];
--
-- For a single managed identity (system-assigned or user-assigned):
--   CREATE USER [uami-sql-deployer] FROM EXTERNAL PROVIDER;
--   ALTER ROLE db_schema_deployer ADD MEMBER [uami-sql-deployer];

CREATE USER [REPLACE_WITH_ENTRA_PRINCIPAL_NAME] FROM EXTERNAL PROVIDER;
ALTER ROLE db_schema_deployer ADD MEMBER [REPLACE_WITH_ENTRA_PRINCIPAL_NAME];
GO

-- 4. Verify the membership.
SELECT
    rp.name  AS RoleName,
    mp.name  AS MemberName,
    mp.type_desc AS MemberType
FROM sys.database_role_members rm
JOIN sys.database_principals rp ON rp.principal_id = rm.role_principal_id
JOIN sys.database_principals mp ON mp.principal_id = rm.member_principal_id
WHERE rp.name = N'db_schema_deployer';
GO
