using CosmosToSqlAssessment.Models.DataFactory;

namespace CosmosToSqlAssessment.Services.DataFactory;

/// <summary>
/// Builds the parameterised ADF linked services. Default emit mode is
/// System-Assigned Managed Identity for both connectors (the modern recommended shape).
/// Key Vault wiring is opt-in via <see cref="DataFactoryGenerationOptions.UseAzureKeyVault"/>.
/// </summary>
public sealed class LinkedServiceBuilder
{
    /// <summary>ADF linked-service type discriminator for Azure Cosmos DB (SQL API) connections.</summary>
    public const string CosmosLinkedServiceType = "CosmosDb";
    /// <summary>ADF linked-service type discriminator for Azure SQL Database connections.</summary>
    public const string AzureSqlLinkedServiceType = "AzureSqlDatabase";
    /// <summary>ADF linked-service type discriminator for Azure Key Vault secret-store connections.</summary>
    public const string KeyVaultLinkedServiceType = "AzureKeyVault";
    /// <summary>Logical artifact name for the single shared Azure SQL linked service emitted across all target tables.</summary>
    public const string AzureSqlLinkedServiceName = "AzureSqlDatabaseLinkedService";
    /// <summary>Logical artifact name for the Azure Key Vault linked service emitted when <see cref="DataFactoryGenerationOptions.UseAzureKeyVault"/> is <c>true</c>.</summary>
    public const string KeyVaultLinkedServiceName = "KeyVaultLinkedService";

    /// <summary>
    /// Builds a parameterised Cosmos DB linked service for <paramref name="databaseName"/>.
    /// Authentication shape is controlled by <see cref="DataFactoryGenerationOptions.UseManagedIdentityForCosmos"/>
    /// and <see cref="DataFactoryGenerationOptions.UseAzureKeyVault"/>: MI (default) emits
    /// <c>accountEndpoint</c> + <c>database</c>; Key Vault emits a connection string with an
    /// AKV secret reference; otherwise a placeholder connection string is written.
    /// </summary>
    /// <param name="databaseName">Source Cosmos DB database name; used to derive a unique linked-service artifact name.</param>
    /// <param name="registry">Name registry for allocating a collision-free artifact name.</param>
    /// <param name="options">Generation options controlling the auth shape and Key Vault wiring.</param>
    /// <returns>A fully constructed <see cref="LinkedServiceResource"/> ready for serialization.</returns>
    public LinkedServiceResource BuildCosmosLinkedService(
        string databaseName,
        AdfNameRegistry registry,
        DataFactoryGenerationOptions options)
    {
        var desiredName = $"CosmosDb_{databaseName}_LinkedService";
        var allocated = registry.Allocate(desiredName, $"linkedService|cosmos|{databaseName}");

        var ls = new LinkedServiceResource
        {
            Name = allocated,
            Properties = new LinkedServiceProperties
            {
                Type = CosmosLinkedServiceType,
                Annotations = new List<string>
                {
                    "Generated by Cosmos to SQL Assessment tool (parent #70, sub-issues #141 & #142).",
                    options.UseManagedIdentityForCosmos
                        ? "Auth: System-Assigned Managed Identity. Requires Cosmos DB Built-in Data Contributor role on the factory MI."
                        : (options.UseAzureKeyVault
                            ? "Auth: account key from Azure Key Vault."
                            : "Auth: placeholder account key. Replace before deployment."),
                },
            },
        };

        // Parameters block on linked service properties (via extension bag).
        var lsParams = new Dictionary<string, object?>();
        foreach (var p in ParameterCatalog.CosmosLinkedServiceParameters(useKeyVault: options.UseAzureKeyVault && !options.UseManagedIdentityForCosmos))
        {
            lsParams[p.Name] = new Dictionary<string, object?> { ["type"] = p.Type };
        }
        ls.Properties.AdditionalProperties = new Dictionary<string, object?>
        {
            ["parameters"] = lsParams,
        };

        if (options.UseManagedIdentityForCosmos)
        {
            // Modern recommended shape — no connection string, no account key.
            ls.Properties.TypeProperties["accountEndpoint"] = $"@{{linkedService().{ParameterCatalog.CosmosAccountEndpoint}}}";
            ls.Properties.TypeProperties["database"] = $"@{{linkedService().{ParameterCatalog.CosmosDatabaseName}}}";
        }
        else if (options.UseAzureKeyVault)
        {
            ls.Properties.TypeProperties["connectionString"] =
                $"AccountEndpoint=@{{linkedService().{ParameterCatalog.CosmosAccountEndpoint}}};Database=@{{linkedService().{ParameterCatalog.CosmosDatabaseName}}};";
            ls.Properties.TypeProperties["accountKey"] = BuildKeyVaultSecretReference(ParameterCatalog.CosmosAccountKeySecretName);
        }
        else
        {
            ls.Properties.TypeProperties["connectionString"] =
                $"AccountEndpoint=@{{linkedService().{ParameterCatalog.CosmosAccountEndpoint}}};AccountKey=<replace-with-account-key>;Database=@{{linkedService().{ParameterCatalog.CosmosDatabaseName}}};";
        }

        return ls;
    }

    /// <summary>
    /// Builds the shared Azure SQL linked service used by every generated sink dataset.
    /// Authentication is controlled by <see cref="DataFactoryGenerationOptions.UseManagedIdentityForSql"/>
    /// and <see cref="DataFactoryGenerationOptions.UseAzureKeyVault"/>: MI (default) emits
    /// <c>server</c> + <c>database</c> + <c>authenticationType=SystemAssignedManagedIdentity</c>;
    /// Key Vault emits a connection string with an AKV password reference; otherwise a placeholder
    /// connection string is written.
    /// </summary>
    /// <param name="registry">Name registry for allocating a collision-free artifact name.</param>
    /// <param name="options">Generation options controlling the auth shape and Key Vault wiring.</param>
    /// <returns>A fully constructed <see cref="LinkedServiceResource"/> ready for serialization.</returns>
    public LinkedServiceResource BuildAzureSqlLinkedService(
        AdfNameRegistry registry,
        DataFactoryGenerationOptions options)
    {
        var allocated = registry.Allocate(AzureSqlLinkedServiceName, "linkedService|azureSql");

        var ls = new LinkedServiceResource
        {
            Name = allocated,
            Properties = new LinkedServiceProperties
            {
                Type = AzureSqlLinkedServiceType,
                Annotations = new List<string>
                {
                    "Generated by Cosmos to SQL Assessment tool (parent #70, sub-issues #141 & #142).",
                    options.UseManagedIdentityForSql
                        ? "Auth: System-Assigned Managed Identity. Requires AAD EXTERNAL PROVIDER user for the factory MI in the target database."
                        : (options.UseAzureKeyVault
                            ? "Auth: SQL authentication with password from Azure Key Vault."
                            : "Auth: placeholder SQL connection string. Replace before deployment."),
                },
            },
        };

        var lsParams = new Dictionary<string, object?>();
        foreach (var p in ParameterCatalog.SqlLinkedServiceParameters(useKeyVault: options.UseAzureKeyVault && !options.UseManagedIdentityForSql))
        {
            lsParams[p.Name] = new Dictionary<string, object?> { ["type"] = p.Type };
        }
        ls.Properties.AdditionalProperties = new Dictionary<string, object?>
        {
            ["parameters"] = lsParams,
        };

        if (options.UseManagedIdentityForSql)
        {
            // Modern recommended Azure SQL connector — server / database / authenticationType.
            ls.Properties.TypeProperties["server"] = $"@{{linkedService().{ParameterCatalog.SqlServerName}}}.database.windows.net";
            ls.Properties.TypeProperties["database"] = $"@{{linkedService().{ParameterCatalog.SqlDatabaseName}}}";
            ls.Properties.TypeProperties["authenticationType"] = "SystemAssignedManagedIdentity";
            ls.Properties.TypeProperties["encrypt"] = "mandatory";
            ls.Properties.TypeProperties["trustServerCertificate"] = false;
        }
        else if (options.UseAzureKeyVault)
        {
            ls.Properties.TypeProperties["connectionString"] =
                $"Server=tcp:@{{linkedService().{ParameterCatalog.SqlServerName}}}.database.windows.net,1433;Database=@{{linkedService().{ParameterCatalog.SqlDatabaseName}}};User ID=@{{linkedService().{ParameterCatalog.SqlUserName}}};";
            ls.Properties.TypeProperties["password"] = BuildKeyVaultSecretReference(ParameterCatalog.SqlPasswordSecretName);
        }
        else
        {
            ls.Properties.TypeProperties["connectionString"] =
                $"Server=tcp:@{{linkedService().{ParameterCatalog.SqlServerName}}}.database.windows.net,1433;Database=@{{linkedService().{ParameterCatalog.SqlDatabaseName}}};";
        }

        return ls;
    }

    /// <summary>
    /// Emits a parameterised Key Vault linked service. Only call when
    /// <see cref="DataFactoryGenerationOptions.UseAzureKeyVault"/> is true.
    /// </summary>
    public LinkedServiceResource BuildKeyVaultLinkedService(AdfNameRegistry registry)
    {
        var allocated = registry.Allocate(KeyVaultLinkedServiceName, "linkedService|keyVault");
        var ls = new LinkedServiceResource
        {
            Name = allocated,
            Properties = new LinkedServiceProperties
            {
                Type = KeyVaultLinkedServiceType,
                Annotations = new List<string>
                {
                    "Generated by Cosmos to SQL Assessment tool (parent #70, sub-issue #142).",
                    "Authentication: System-Assigned Managed Identity. Factory MI must have Key Vault Secrets User on the target vault.",
                },
            },
        };
        ls.Properties.TypeProperties["baseUrl"] = $"@{{linkedService().{ParameterCatalog.KeyVaultBaseUrl}}}";

        var lsParams = new Dictionary<string, object?>();
        foreach (var p in ParameterCatalog.KeyVaultLinkedServiceParameters())
        {
            lsParams[p.Name] = new Dictionary<string, object?> { ["type"] = p.Type };
        }
        ls.Properties.AdditionalProperties = new Dictionary<string, object?>
        {
            ["parameters"] = lsParams,
        };
        return ls;
    }

    private static Dictionary<string, object?> BuildKeyVaultSecretReference(string secretNameParameter) => new()
    {
        ["type"] = "AzureKeyVaultSecret",
        ["store"] = new Dictionary<string, object?>
        {
            ["referenceName"] = KeyVaultLinkedServiceName,
            ["type"] = "LinkedServiceReference",
        },
        ["secretName"] = $"@{{linkedService().{secretNameParameter}}}",
    };
}
