using CosmosToSqlAssessment.Models;
using CosmosToSqlAssessment.Models.DataFactory;

namespace CosmosToSqlAssessment.Services.DataFactory;

/// <summary>
/// Builds the two foundational ADF linked services (one Cosmos DB SQL API linked
/// service per source database, plus a single Azure SQL Database linked service).
/// Connection details intentionally use placeholder ADF expressions — full
/// parameterization lands in #142.
/// </summary>
public sealed class LinkedServiceBuilder
{
    public const string CosmosLinkedServiceType = "CosmosDb";
    public const string AzureSqlLinkedServiceType = "AzureSqlDatabase";
    public const string AzureSqlLinkedServiceName = "AzureSqlDatabaseLinkedService";

    public LinkedServiceResource BuildCosmosLinkedService(string databaseName, AdfNameRegistry registry)
    {
        var desiredName = $"CosmosDb_{databaseName}_LinkedService";
        var allocated = registry.Allocate(desiredName, $"linkedService|cosmos|{databaseName}");

        return new LinkedServiceResource
        {
            Name = allocated,
            Properties = new LinkedServiceProperties
            {
                Type = CosmosLinkedServiceType,
                TypeProperties =
                {
                    // Placeholder; #142 swaps this for a parameter reference.
                    ["connectionString"] = $"AccountEndpoint=<cosmos-account-endpoint>;AccountKey=<cosmos-account-key>;Database={databaseName};",
                },
                Annotations = new List<string>
                {
                    "Generated by Cosmos to SQL Assessment tool (parent #70, sub-issue #141).",
                    "Connection string placeholder — replace with parameter reference in #142.",
                },
            },
        };
    }

    public LinkedServiceResource BuildAzureSqlLinkedService(AdfNameRegistry registry)
    {
        var allocated = registry.Allocate(AzureSqlLinkedServiceName, "linkedService|azureSql");

        return new LinkedServiceResource
        {
            Name = allocated,
            Properties = new LinkedServiceProperties
            {
                Type = AzureSqlLinkedServiceType,
                TypeProperties =
                {
                    ["connectionString"] = "Server=tcp:<sql-server>.database.windows.net,1433;Database=<sql-database>;",
                    // #142 will swap to AAD / managed identity authentication.
                },
                Annotations = new List<string>
                {
                    "Generated by Cosmos to SQL Assessment tool (parent #70, sub-issue #141).",
                    "Connection string placeholder — replace with parameter reference in #142.",
                },
            },
        };
    }
}
